### PR TITLE
Android 2.13 Nougat Hotfix #1

### PR DESCRIPTION
**Pull request by pdrj**
## What's this?
This is a hotfix that handles the most common crash on 2.13.

## Changelog
- Added new onboarding and sign in views
- Fixed non-selectable projects and tags
- Fixed a startup crash happening in specific locales
- Other fixes and improvements

## Changes
https://github.com/toggl/mobileapp/compare/android-2.12-1...hotfix/android-2.13.1

## :squid: Permissions
Me

### CODE REVIEW

**Comment by heytherewill** [comment]
Does this really fix the crash? 🤔

**Comment by pdrj** [comment]
Yes, as said in Daivid's PR.

**Comment by daividssilverio** [comment]
Changelog looks good (it's the same, right?)

**Comment by pdrj** [comment]
It only has one more item @daividssilverio:
> Fixed a startup crash happening in specific locales

**Pull request merged**
