### PR TITLE
Use the signup endpoint in integration tests

### LINKED ISSUE #930: Use v9 signup endpoint for integration tests
Replace the hacky v8 signup call. Do this one once the v9 endpoint is in production and we are confident that it works well.

### PR DESCRIPTION
**Pull request by simonrozsival**
Closes #930 

On hold: Right now the endpoint doesn't seem very stable - _sometimes_ it returns 200, but default workspace is `null` and so deserialization fails (also probably it won't work even if handled it correctly, because we need the workspace in most cases). Also I got a 500 once. We can merge this once these two backend bugs are fixed.

### CODE REVIEW

**Comment by amulware** [comment]
No update on this yet?

**Comment by simonrozsival** [comment]
The backend issues were postponed to yet another milestone an hour ago.

**Comment by simonrozsival** [comment]
Update: backend guys are working on these issues atm.

**Comment by simonrozsival** [comment]
Integration tests: https://www.bitrise.io/build/d649ec67efff1d89

**Pull request merged**
