### PR TITLE
Add ConnectedReplay extension

### PR DESCRIPTION
**Pull request by amulware**
Just a little extension that has come in handy in at least two different places so far.

### CODE REVIEW

**Comment by amulware** [comment]
I can't do packages -.-

**Comment by amulware** [comment]
I won't pretend I really understand what I did.

**Comment by amulware** [comment]
@willsb Do you want to look over the changes to the packages?

**Comment by willsb** [comment]
Why did you update FluentAssertions?

**Comment by amulware** [comment]
VS did on its own. I can remove that if you want.

**Comment by willsb** [comment]
You should. Not only those are changes unrelated, some are actually problematic (One does not simply update Rx to 3.1.1)

**Comment by amulware** [comment]
Manually editing project files. Anything else @willsb?

**Comment by willsb** [comment]
Merge away :)

**Pull request merged**
