### PR TITLE
Common data sources layer

### PR DESCRIPTION
**Pull request by willsb**

### CODE REVIEW

**Comment by amulware** [comment]
I disagree with these changes. I see no benefit in having a common interface, since db and api will behave very differently.

**Comment by willsb** [comment]
The common interface is for the source that Foundation will consume. Both it and API (and possibly the memory storage) will have the same interface

**Comment by amulware** [comment]
I don't understand how that answers my point. We already have an interfaces for the API that will work just fine.

**Comment by willsb** [comment]
Closing for the time being.

**Pull request closed without merging**
