### PR TITLE
Add BaseStorage.GetAll() method

### PR DESCRIPTION
**Pull request by arturs105**

### CODE REVIEW

**Comment by amulware** [comment]
What is this for?

**Comment by arturs105** [comment]
If we wanted to get all data without filtering, then the `GetAll(Func<T, bool>)` method would have to be called like this `GetAll(_ => true)`. It would probably have to call the lambda expression for all instances in the database, which is a waste of function calls if we want to get completely everything.

**Comment by amulware** [comment]
To be able to use it, it would have to be exposed in `IRepository<>` though, right?

**Comment by arturs105** [comment]
Yup, you're right.

**Pull request merged**
