### PR TITLE
Fix base authentication test for unauthenticated users flakiness

### PR DESCRIPTION
**Pull request by daividssilverio**
Closes nothing.

Part of #2528 

How does it remove the flakiness? By accepting either 401 and 403 possible status code responses when making requests with invalid credentials.

https://github.com/toggl/mobileapp/blob/develop/Toggl.Ultrawave/ApiClients/BaseApi.cs#L159 isn't enough because that piece of code expects the user to be logged in to handle 403 as an Unauthorized error, instead of an Unauthenticated error. The test affected by this PR is actually made with invalid credentials.

### CODE REVIEW

**Comment by daividssilverio** [comment]
Integration tests: https://app.bitrise.io/build/62701b7b746ac17a

**Comment by amulware** [comment]
Is our business logic also catching both exceptions? I.e. is the test in line with how the app behaves?

**Comment by daividssilverio** [comment]
Well, actually, this test is kind of weird now that you've mentioned that.

Our business logic (inside Foundation and Foundation.MvvmCross) handles only `UnauthorizedException` directly. Otherwise, the code you mentioned will handle Forbidden exceptions by making another request and checking whether or not we are getting user-related status errors.

Anyway, `AuthenticatedEndpointBaseTests` is the base for a lot of api tests, and it covers all calls with ApiTokens and Simple authentication. And that's not how things are done in the code base. As far as I understood, we are only making `WithPassword` calls when doing Login/SignUp/RefreshToken, and after that api calls are made using api tokens.

Does it make sense to have the Base test as it is?

**Comment by amulware** [comment]
I'm not sure I understand what you're saying. The code referenced (https://github.com/toggl/mobileapp/blob/develop/Toggl.Ultrawave/ApiClients/BaseApi.cs#L159) Should catch all `Forbidden` and turn them into `Unauthorized` if the `/me/logged` returns a 4xx error.

I just tested this locally, and that endpoint indeed returns a 403 if I use a wrong password or non-existent user.

So how can the 403 (Forbidden) ever escape Ultrawave?

**Comment by daividssilverio** [comment]
I'm closing this PR because it does not actually fix anything.
As talked internally, the exception that used to make our tests fail actually happens on our tests while setting up the user for the test.
This has became quite stable and it might have been just a matter of bad timing with the staging db flush.
Since our tests are now running before the flush and after db switches, this should be fine.
We can look at it again if happens again.
This might still happen if you run your tests around the time backend flushes staging data.

**Comment by daividssilverio** [comment]
Oh, just over communicating a little, but as you said, 403 (Forbidden) do not escape Ultrawave. They are wrapped around Unauthorized.

**Pull request closed without merging**
