### PR TITLE
Fix some navigation problems on Giskard

### LINKED ISSUE #3152: Giskard crashes on edit screen after going to another sub screen, going home and back
## 💥 Crash Report
It looks like we are having some trouble with the mvx navigation when going to sub screens.
The app will crash if you:
1. click on an existing TE to edit
2. click the project selection box
3. check your projects, select one (or not)
4. still in the projects screen, or any other subscreen after that, press home
5. go back to the app
6. try pressing UP (<-) or the back button.
7. navigation will either not work or you will get the crash below

### 👥 Impact
Well, this affects anyone trying to create/select a project/client/task in the edit view and for some reason checking something else in another app or just by having a low-end phone.

### 🔗 Context
There was one at some point but I couldn't find it. The one about creating a project not redirecting the user back to the edit view.

### 🛰 Link
Didn't find it.

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
                         E    at Toggl.Foundation.MvvmCross.ViewModels.EditTimeEntryViewModel.get_isDirty () [0x00000] in <44bf0fd1c67d4889808313f6903411d3>:0
                         E    at Toggl.Foundation.MvvmCross.ViewModels.EditTimeEntryViewModel+<closeWithConfirmation>d__163.MoveNext () [0x0001a] in <44bf0fd1c67d48898
                            08313f6903411d3>:0
                         E  --- End of stack trace from previous location where exception was thrown ---
                         E    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <b0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <b0b794627e4d420a98d0f9
                            ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <b
                            0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <b0b794627e4d420a98d0f9ff8a6f9
                            f8a>:0
                         E    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <b0b794627e4d420a98d0f9ff8a6f9
                            f8a>:0
                         E    at MvvmCross.Commands.MvxAsyncCommandBase+<ExecuteConcurrentAsync>d__17.MoveNext () [0x0010e] in <40677de5759e4839936aaead0d9b235f>:0
                         E  --- End of stack trace from previous location where exception was thrown ---
                         E    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <b0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <b0b794627e4d420a98d0f9
                            ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <b
                            0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <b0b794627e4d420a98d0f9ff8a6f9
                            f8a>:0
                         E    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <b0b794627e4d420a98d0f9ff8a6f9
                            f8a>:0
                         E    at MvvmCross.Commands.MvxAsyncCommandBase+<ExecuteAsync>d__16.MoveNext () [0x00085] in <40677de5759e4839936aaead0d9b235f>:0
                         E  --- End of stack trace from previous location where exception was thrown ---
                         E    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <b0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <b0b794627e4d420a98d0f9
                            ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <b
                            0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <b0b794627e4d420a98d0f9ff8a6f9
                            f8a>:0
                         E    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in <b0b794627e4d420a98d0f9ff8a6f9
                            f8a>:0
                         E    at MvvmCross.Commands.MvxAsyncCommandBase+<Execute>d__14.MoveNext () [0x0009a] in <40677de5759e4839936aaead0d9b235f>:0
                         E  --- End of stack trace from previous location where exception was thrown ---
                         E    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <b0b794627e4d420a98d0f9ff8a6f9f8a>:0
                         E    at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <b0b794627e4d420a98d0
                            f9ff8a6f9f8a>:0
                         E    at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <581558e7504c49cea49d1900b3755df6>:0
                         E    at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <581558e7504c49cea49d1900b3755df6>:0
                         E    at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <581558e7504c49cea49d1900b3755df6>:0
                         E    at (wrapper dynamic-metho
```

### PR DESCRIPTION
**Pull request by daividssilverio**
## What's this?
This is a quick fix around the navigation problems some of our views have been showing.
More specifically:
- [x] Select project screen
- [x] Create project screen
- [x] Select client screen
- [ ] Maybe something else
### Relationships
The source of the problem is the same that originated #2807

Closes #3152

## Why do we want this?
Sometimes, on some devices, we can get stuck on some views because the `CurrentActivity` is selected by the presentation layer provided by Mvx.

## How is it done?
I abuse of the `QueryableMvxLifecycleMonitorCurrentTopActivity` created to fix #2807 and look for the right viewModel to be closed.

### Why not another way?
The right thing to do would be actually fixing the source problem on MvvmCross. I, or someone else can do that later. But that takes more time and effort.

### Side effects
There shouldn't be any. Unless we start closing VMs that are not in the logical top of the VMs's stack.

## Review hints
Try replicating the problem in question in develop.
Try replicating it here.
The changes themselves are quite simple.

## :squid: Permissions
🦑 whenever

### CODE REVIEW

**Comment by dshr** [comment]
Does not seem to work for me — I'm still either getting the crashes from #3152 or just freezes 😢

In #3152, when you said "Press home" you meant the ● button, not the ◼︎ one, right? Bc it all works fine with ◼︎ even on `develop`.

**Comment by dshr** [comment]
After more testing and poking around, I've stopped getting the crashes, only Splashscreens now. Might've been a dirty build.

**Comment by dshr** [comment]
Managed to get the Splashscreen problem to go away. It shows up bc of `MainLauncher = true`, and then stay behind bc nothing ever tells it to finish, since we're not going through the normal setup process. We can handle that by closing the Splash activity manually like this:
```csharp
// SplashScreen.cs
protected override void RunAppStart(Bundle bundle)
{
    base.RunAppStart(bundle);
    var navigationUrl = Intent.Data?.ToString();
    if (string.IsNullOrEmpty(navigationUrl))
    {
        Finish();
        return;
    }

    Mvx.Resolve<IMvxNavigationService>().Navigate(navigationUrl);
}
```
This will obv clash with 1.4 so we're have to exercise caution when merging.

**Comment by daividssilverio** [comment]
neon got merged into this branch. 🤔 @dshr can you share more about the freeze you are getting?
I tried on Android 8, 7.1 (emulator) and 6.0 but I can't reproduce the crashes or freezes. Can you also do a fully clean build and test again please? Let me know what you find.

**Comment by dshr** [comment]
_Phresh emulator, who dis?_
So yeah, factory reset the emu, "Clean Al", and built. Logged into test acc, resumed a TE, opened the Edit TE view, clicked on "Add Project", then tapped home, opened the app from the launcher and got `Object reference not set to an instance of an object.`.

The Splash was happening when starting a brand new TE **and** creating a brand new project. Now, after doing the "home -> open from launcher" dance, when I get back to the app, I get to the main screen, and the time entry has been discarded. Going back via recent apps works perfectly.

**Comment by daividssilverio** [comment]
@dshr , could add another issue for the problem you described?
Unless there's a bug in this implementation itself.

**Comment by kornelijepetak** [comment]
I have no idea what's going on. I can't reproduce what's described in the issue at all on `develop` so I am not sure how to test whether the fix actually works, although the code makes sense. The only way I did get this kind of error (and even then I was not sure if that's related) is when I turned on `Don't keep activities'. In that case, I was still able to return from the Project screen to the Edit TE screen by pressing back button. However, the Edit screen was messed up data-wise. Empty fields, `default(DateTimeOffset)`... Then when I tapped the project field to select another project, it crashed with this error. :boom: Without this option set, it worked normally. Tested several times with different screens.

Doing what @dshr suggested however, I'm getting that same error (at least it seems the same).
So: opening any of those screens, homing and then starting the app from launcher crashes with nullref. However, once this happens once, I can't reproduce it consistently anymore in future attempts. Messed up.

**Comment by daividssilverio** [comment]
🤔 Can you replicate the crash you are talking about in develop? I don't think this branch is introducing that.

**Comment by kornelijepetak** [comment]
It happens in develop as well, so I am not saying that your PR introduces it. I'm just thinking how it's related since the error your issue describes seems to be the same error (exception-wise) that what me and @dshr mentioned.

**Pull request merged**
