### PR TITLE
⬆ Update ruleset

### PR DESCRIPTION
**Pull request by kornelijepetak**
## What's this?
Proposition to activate more stylecop rules.

### Relationships
Discusses #1947.

## Why do we want this?
Code quality and streamlining.

## How is it done?
This PR changes the .ruleset file to a proposition that needs to be discussed.
The comment below gives the table to make things simpler.

### Side effects
The code can't be built with this ruleset because it breaks some of them. Let's first discuss and agree on the ruleset, then I will fix the code to conform.

## Review hints
I've tried to help with the table as much as I could.

## :squid: Permissions
Not yet.

### CODE REVIEW

**Comment by kornelijepetak** [comment]
Existing rules were not changed.

---

**LEGEND:**
* ⚠ WARNING
* ⛔ ERROR

---

|CODE|Action|Description|
|:-:|:-:|:-|
|[1102](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1102.md)|⚠|A C# query clause does not begin on the same line as the previous clause, or on the next line| 
|[1103](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1103.md)|⚠|The clauses within a C# query expression are not all placed on the same line, and each clause is not placed on its own line| 
|[1104](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1104.md)|⚠|A clause within a C# query expression begins on the same line as the previous clause, when the previous clause spans across multiple lines| 
|[1105](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1105.md)|⚠|A clause within a C# query expression spans across multiple lines, and does not begin on its own line| 
|[1106](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1106.md)|⛔|The C# code contains an extra semicolon| 
|[1107](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1107.md)|⚠|The C# code contains more than one statement on a single line| 
|[1108](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1108.md)|⛔|A C# statement contains a comment between the declaration of the statement and the opening brace of the statement| 
|[1112](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1112.md)|⛔|The closing parenthesis or bracket in a call to a C# method or indexer, or the declaration of a method or indexer, is not placed on the same line as the opening bracket when the element does not take any parameters| 
|[1114](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1114.md)|⚠|The start of the parameter list for a method or indexer call or declaration does not begin on the same line as the opening bracket, or on the line after the opening bracket| 
|[1115](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1115.md)|⚠|A parameter within a C# method or indexer call or declaration does not begin on the same line as the previous parameter, or on the next line| 
|[1120](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1120.md)|⛔|The C# comment does not contain any comment text| 
|[1121](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1121.md)|⚠|The code uses one of the basic C# types, but does not use the built-in alias for the type| 
|[1125](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1125.md)|⛔|The Nullable type has been defined not using the C# shorthand. For example, Nullable<DateTime> has been used instead of the preferred DateTime?| 
|[1134](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1134.md)|⛔|An attribute is placed on the same line of code as another attribute or element| 
|[1205](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1205.md)|⛔|The partial element does not have an access modifier defined| 
|[1206](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1206.md)|⚠|The keywords within the declaration of an element do not follow a standard ordering scheme| 
|[1208](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1208.md)|⛔|A using directive which declares a member of the System namespace appears after a using directive which declares a member of a different namespace, within a C# code file| 
|[1209](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1209.md)|⛔|A using-alias directive is positioned before a regular using directive| 
|[1212](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1212.md)|⛔|A get accessor appears after a set accessor within a property or indexer| 
|[1302](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1302.md)|⛔|The name of a C# interface does not begin with the capital letter I| 
|[1306](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1306.md)|⚠|The name of a field in C# does not begin with a lower-case letter| 
|[1307](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1307.md)|⛔|The name of a public or internal field in C# does not begin with an upper-case letter| 
|[1308](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1308.md)|⛔|A field name in C# is prefixed with m_ or s_| 
|[1309](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1309.md)|⛔|A field name in C# begins with an underscore| 
|[1310](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1310.md)|⚠|A field name in C# contains an underscore| 
|[1312](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1312.md)|⛔|The name of a variable in C# does not begin with a lower-case letter| 
|[1400](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1400.md)|⛔|The access modifier for a C# element has not been explicitly defined| 
|[1401](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1401.md)|⚠|A field within a C# class has an access modifier other than private| 
|[1500](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1500.md)|⛔|The opening or closing brace within a C# statement, element, or expression is not placed on its own line| 
|[1501](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1501.md)|⚠|A C# statement containing opening and closing braces is written completely on a single line| 
|[1505](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1505.md)|⚠|An opening brace within a C# element, statement, or expression is followed by a blank line| 
|[1506](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1506.md)|⚠|An element documentation header above a C# element is followed by a blank line| 
|[1508](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1508.md)|⚠|A closing brace within a C# element, statement, or expression is preceded by a blank line| 
|[1509](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1509.md)|⚠|An opening brace within a C# element, statement, or expression is preceded by a blank line| 
|[1510](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1510.md)|⛔|Chained C# statements are separated by a blank line| 
|[1511](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1511.md)|⛔|The while footer at the bottom of a do-while statement is separated from the statement by a blank line| 
|[1513](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1513.md)|⚠|A closing brace within a C# element, statement, or expression is not followed by a blank line| 
|[1514](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1514.md)|⛔|An element documentation header above a C# element is not preceded by a blank line| 
|[1517](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1517.md)|⛔|The code file has blank lines at the start| 
|[1519](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1519.md)|⛔|The opening and closing braces for a multi-line C# statement have been omitted| 
|[1520](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1520.md)|⛔|The opening and closing braces of a chained if/else if/else construct were included for some clauses, but omitted for others|

**Comment by heytherewill** [comment]
1121, 1206, 1306, 1401 should be errors, IMO

Is there a rule to not allow BOMs?

**Comment by kornelijepetak** [comment]
You are indeed right, @heytherewill. Maybe they should be errors.

Re: the BOM, there's [SA1412](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1412.md) which requires UTF-8 with BOM. Couldn't find anything else.

**Comment by sofokli1** [comment]
@kornelijepetak I agree with the point from the above comments and the PR itself. Is there a way to disable this checks easily when you just want to test something and do not care about code quality (yet you want to run it on the simulator), but enable them before committing the code (when cleaning up)?

**Comment by kornelijepetak** [comment]
@sofokli1 Every link to the StyleCop page has a `How to suppress violations` [section at the bottom](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1505.md#how-to-suppress-violations). 

It's as easy as wrapping your code into a `#pragma warning disable/restore` directive.

```cs
#pragma warning disable SA1302 // InterfaceNamesMustBeginWithI

public interface ThisInterfaceSucks
{

}

#pragma warning restore SA1302 // InterfaceNamesMustBeginWithI
```

**Comment by heytherewill** [comment]
@kornelijepetak BTW, how many errors/warnings do you get with this configuration? How easy would it be to enable those rules, code change wise?

I ask because we are about to change *a lot* of our codebase

**Comment by kornelijepetak** [comment]
@heytherewill Quite a lot of errors/warnings. Order of magnitude 100-200. 

But this is fixable in a few hours. However, it is quite difficult to properly merge into our codebase with all the open PRs. Ideally, 0 PRs would be great at that time, but that will never happen.

If you have a suggestion of how to do it with as little pain, I'm all ears.

I thought that maybe we could do it in phases so that even if there's something to fix/merge, it's not as many changes at once.

**Comment by heytherewill** [comment]
I would definitely wait until after we MVExit before working on this. I think the ideal point in time would be alongside with turning nullable reference types on for the codebase

**Comment by heytherewill** [comment]
Closing as obsolete

**Pull request closed without merging**
