### PR TITLE
Fix SelectableTagBaseViewModel identity

### LINKED ISSUE #5691: IllegalStateException on RecyclerView.handleMissingPreInfoForChangeError
## 💥 Crash Report
It seems to be happening when selecting tags. This might be already fixed on #5624

### 👥 Impact
Affecting a total of 398 users, with a total of 1254 reports.
Reached 0.4% of our users in the last 30 days on droid 2.0.1

### 🔗 Context
Seems to be related to #5569, except that one happens when creating tags.

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/2601266145u/overview
and https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/1176162990u/reports

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{8325106 position=1 id=-1245970500, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ViewHolder{7c0f560 position=0 id=-1245970500, oldPos=-1, pLpos:-1} android.support.v7.widget.RecyclerView{ad967d5 VFED.V... ......ID 0,168-1080,887 #7f0d01e9 app:id/SelectTagsRecyclerView}, adapter:md5e6930ea5438967c9497bdc857a01d090.SelectTagsRecyclerAdapter@e487f2e, layout:android.support.v7.widget.LinearLayoutManager@ff24bea, context:md56d31f6f2c59878fdf075cc45b4e7258a.SelectTagsActivity@80f0da9
  at android.support.v7.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4058)
  at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3982)
  at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3652)
....
```

### LINKED ISSUE #5692: IndexOutOfBoundsException on RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline
## 💥 Crash Report
It seems to be a crash that happens when adding/selecting tags.

### 👥 Impact
I has affected 167 users, with 446 occurrences; 
About 0.2% of our users in the last 30 days. 

### 🔗 Context
Very similar to #5691 and possibly #5569
Could have been already fixed by #5624

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/917105280u/overview

### 📝  Exception & Stack Trace
`Exception type and message`
```cs
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:-1).state:12 android.support.v7.widget.RecyclerView{f6b25a3 VFED.V... ......ID 0,168-1080,1050 #7f0d01e9 app:id/SelectTagsRecyclerView}, adapter:md5e6930ea5438967c9497bdc857a01d090.SelectTagsRecyclerAdapter@fab1958, layout:android.support.v7.widget.LinearLayoutManager@528e0a0, context:md56d31f6f2c59878fdf075cc45b4e7258a.SelectTagsActivity@bd46e3b
  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5923)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
...
```

### LINKED ISSUE #5820: Multiple crashes in recycler views
## 💥 Crash Report
Users report that trying to type anything in the text box of the tag selection view (opened from the edit view) crashes the app.

### 👥 Impact
- 5% of total crashes on 2.2.1

### 🔗 Context
- Could be the same as #5691
- and perhaps related to #5692

### 🛰 Link
https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3633119050u/overview

### 📝  Exception & Stack Trace
```cs
android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline
RecyclerView.java, line 5923
```
`
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:-1).state:13 android.support.v7.widget.RecyclerView{9bf8678 VFED.V... ......ID 0,196-1440,1731 #7f0d01ee app:id/SelectTagsRecyclerView}, adapter:md5e6930ea5438967c9497bdc857a01d090.SelectTagsRecyclerAdapter@82aa065, layout:android.support.v7.widget.LinearLayoutManager@a550151, context:md56d31f6f2c59878fdf075cc45b4e7258a.SelectTagsActivity@582a55c
`
```cs
android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline RecyclerView.java:5923
android.support.v7.widget.RecyclerView$Recycler.getViewForPosition RecyclerView.java:5858
android.support.v7.widget.RecyclerView$Recycler.getViewForPosition RecyclerView.java:5854
android.support.v7.widget.LinearLayoutManager$LayoutState.next LinearLayoutManager.java:2230
android.support.v7.widget.LinearLayoutManager.layoutChunk LinearLayoutManager.java:1557
android.support.v7.widget.LinearLayoutManager.fill LinearLayoutManager.java:1517
android.support.v7.widget.LinearLayoutManager.onLayoutChildren LinearLayoutManager.java:622
android.support.v7.widget.RecyclerView.dispatchLayoutStep1 RecyclerView.java:3875
android.support.v7.widget.RecyclerView.dispatchLayout RecyclerView.java:3639
android.support.v7.widget.RecyclerView.onLayout RecyclerView.java:4194
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.support.design.widget.CoordinatorLayout.layoutChild CoordinatorLayout.java:1183
android.support.design.widget.CoordinatorLayout.onLayoutChild CoordinatorLayout.java:870
android.support.design.widget.CoordinatorLayout.onLayout CoordinatorLayout.java:889
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.widget.FrameLayout.layoutChildren FrameLayout.java:323
android.widget.FrameLayout.onLayout FrameLayout.java:261
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.widget.LinearLayout.setChildFrame LinearLayout.java:1812
android.widget.LinearLayout.layoutVertical LinearLayout.java:1656
android.widget.LinearLayout.onLayout LinearLayout.java:1565
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.widget.FrameLayout.layoutChildren FrameLayout.java:323
android.widget.FrameLayout.onLayout FrameLayout.java:261
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.widget.LinearLayout.setChildFrame LinearLayout.java:1812
android.widget.LinearLayout.layoutVertical LinearLayout.java:1656
android.widget.LinearLayout.onLayout LinearLayout.java:1565
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.widget.FrameLayout.layoutChildren FrameLayout.java:323
android.widget.FrameLayout.onLayout FrameLayout.java:261
com.android.internal.policy.DecorView.onLayout DecorView.java:903
android.view.View.layout View.java:20715
android.view.ViewGroup.layout ViewGroup.java:6202
android.view.ViewRootImpl.performLayout ViewRootImpl.java:2812
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2339
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1479
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:7258
android.view.Choreographer$CallbackRecord.run Choreographer.java:1050
android.view.Choreographer.doCallbacks Choreographer.java:862
android.view.Choreographer.doFrame Choreographer.java:797
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:1036
android.os.Handler.handleCallback Handler.java:874
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:198
android.app.ActivityThread.main ActivityThread.java:6729
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:493
com.android.internal.os.ZygoteInit.main ZygoteInit.java:876
```

### PR DESCRIPTION
**Pull request by kornelijepetak**
## What's this?
Fixes identity calculation in SelectableTagBaseViewModel and inheriting classes.

`GetHashcode` should never be used to determine identity!

* Also switches tuple for a proper type.

### Relationships
There's no guarantee that it fixes the following, but it actually might. There are also other issues that might have fixed the following as well. We are not sure. So, I'll make them closed, and we'll reopen them if we see the crash again.

Closes #5691

## Why do we want this?
No crashes. And also for philosophical reasoning about identity.

## How is it done?
Removing hash-code based identity and resorting to equality.

### Why not another way?
An alternative would be to use the ID of 0 for `+ Create new tag` item and the database ID for the tags. While in practice that would work (as we are not using 0 as an ID), I am uneasy about it because it's not really semantically correct.
That's why I decided to make things just equatable.

### Side effects
Should be none. The check is not as big and we are not expecting that many tags in the first place.

## :squid: Permissions
Feel free to.

### CODE REVIEW

**Comment by daividssilverio** [comment]
Hey @kornelijepetak , I approve most of your changes overall, I disagree with the changes made in the `SelectableTagBaseViewModel`.

We were using `IDiffableByIdentifier` to  provide a way for a model to have an Identifier that could be used in the `IdentifierEqualityDiffingStrategy`. If we always compare items with equals, we'll never detect partial changes in `RecyclerViews` that are using our base `DiffUtil`s because:
Item A `(Id = 1, PropX: X, PropY: Y)` and Item B `(Id = 1, PropX: Y, PropY: Z)` would be considered different items since their identities are ignored.

Could you still fix the problems in the original issues while keeping `SelectableTagBaseViewModel` implementing `IDiffableByIdentifier` but without using the `HashCode` as means of identity?

**Comment by kornelijepetak** [comment]
@daividssilverio thanks for the comment.

Short answer: **no (at least not in a nice way)**.

Long answer: `IDiffableByIdentifier<T>` provides a `long Identifier` property. Only if all the possible instances of the type `T` can be uniquely identified across a `long` domain, should this interface be used on the entity.

In the above example, we are using `SelectableTagBaseViewModel` as the type `T`. Since that is an abstract class, we need to make sure that those identifiers can be unique across all the possible instances of all deriving classes. So far we have two deriving classes, `SelectableTagViewModel` and `SelectableTagCreationViewModel`. The former has a unique `long` ID across all instances of the `SelectableTagViewModel` type. Unfortunately, that covers all the possible values in the `long` range. That leaves no number that can safely be used as an identifier for the `SelectableTagCreationViewModel`. Thus, it is not possible to guarantee the uniqueness of the identifier for an item and so the `IDiffableByIdentifier<T>` can't be used.

However, that is all under the assumption that 
1) the DB id of entities can be any negative or non-negative number (including 0)
2) there is a possibility to introduce any other class deriving from the `SelectableTagBaseViewModel`

If we ditch both assumptions and can guarantee that
1) Value of 0 will never be used for a tag ID (positive numbers are used by API and negative by Realm for unsynced IDs)
2) We will never introduce any other class deriving from `SelectableTagBaseViewModel`

we can do the following:

1. Make the `SelectableTagBaseViewModel` class implement `IDiffableByIdentifier<SelectableTagBaseViewModel>` again
2. Use the DB ID value of a tag for `SelectableTagViewModel` as the identifier
3. Use the value of 0 for `SelectableTagCreationViewModel` as the identifier

Without those assumptions, the identity calculation will be mathematically and semantically incorrect.

The other option would be to implement a custom `IDiffableStrategy` for tags and depending on the type, use `AreItemsTheSame` and `AreContentsTheSame` methods correctly to avoid reevaluation of `Equals` when it's not really needed. But that will solve the issue for the Android only. I don't think iOS is using diffing strategies at all.

If it was up to me, I would use an interface for diffing that instead of providing the `long Identifier` or `Equals`, instead provides `AreItemsTheSame` and `AreContentsTheSame` methods.

Note that what you are suggesting helps only a bit with performance (albeit very marginally), not with the correctness.

**Comment by kornelijepetak** [comment]
@daividssilverio 

I've changed things back to `IDiffableByIdentifier`, but because of the volatile nature of this surrogate identifier, I insist on leaving the comment there. For posterity.

**Comment by daividssilverio** [comment]
Hey @kornelijepetak , thanks for the changes.

> If it was up to me, I would use an interface for diffing that instead of providing the long Identifier or Equals, instead provides AreItemsTheSame and AreContentsTheSame methods.

I agree with you. I think the performance hit from redirection would be marginal if we did that. Would you create an issue to investigate and maybe improve this for our adapters? pinging @heytherewill because architect.

**Comment by daividssilverio** [comment]
Hey, I got a crash when filtering the tags in the `EditTimeEntryActivity`.
```
 java.lang.IndexOutOfBoundsException: Inconsistency detected. 
Invalid item position 4(offset:-1).state:11 android.support.v7.widget.RecyclerView{99f2f1e VFED.V.. ......ID 0,168-1080,911 #7f0d01fd app:id/SelectTagsRecyclerView}, adapter:md5e6930ea5438967c9497bdc857a01d090.SelectTagsRecyclerAdapter@138f91e9, layout:android.support.v7.widget.LinearLayoutManager@1cd08015, context:md56d31f6f2c59878fdf075cc45b4e7258a.SelectTagsActivity@e6e1a70
```

So, I'm guessing your PR does not close #5820 and #5692

**Comment by kornelijepetak** [comment]
So far the only thing I've found with this error when using a DiffUtil is when a change is pushed to DiffUtil for update while there's an update already in progress... Or when an update happens from another thread. However, I've looked very carefully in our code and something like this can't happen.

When a new change comes in, if the diffutil is already working on a changeset, the new change is only stored, not applied immediately. When diffutil is done, if there's a stored changeset, it is taken and applied. No two calls to diffutil are being done at the same time...

Also, we are scheduling the actual dispatch of changes to a main thread, so recyclerview is always accessed from the correct thread... 🤔

**Comment by kornelijepetak** [comment]
@daividssilverio let's proceed with this PR. I've removed `Closing #XXXX` from the description for the two issues that are not solved by the PR, but the #5961 most likely is solved by this, so let's go with this.

**Pull request merged**
