### PR TITLE
Neon - Giskard 1.4

### PR DESCRIPTION
**Pull request by kornelijepetak**
> **The true color of Neon.**
> 
> When low pressure neon gas is electrified, it glows reddish orange. This is the true color of neon lights. Other colors of lights are produced by coating the interior of the glass with phosphors. 

The change log is as the following:

```
- Added UNDO feature after deleting time entries by swiping
- Added notifications for idle and running time entry (enable in settings)
- Added in-app feedback form (let us know what you think!)

- Improved syncing process
- Improved application behaviour on slower networks
- Improved performance and stability
- Improved onboarding hints

- Other various bug fixes and UI tweaks
```

### CODE REVIEW

**Comment by kornelijepetak** [comment]
Detailed [changelong](https://github.com/toggl/mobileapp/compare/giskard-1.3.2-the-real-deal...neon) can be seen here: 

https://github.com/toggl/mobileapp/compare/giskard-1.3.2-the-real-deal...neon

**Comment by amulware** [comment]
Shouldn't the link above be https://github.com/toggl/mobileapp/compare/giskard-1.3.2...neon to exactly correspond to the changes since the last release tag?

**Comment by kornelijepetak** [comment]
Yes, it should.

**Comment by amulware** [comment]
:doit: but 🚫 🦑

**Pull request merged**
