### PR TITLE
Android 2.7.1 - Hanakazura (花かずら) hotfix

### PR DESCRIPTION
**Pull request by daividssilverio**
## What's this?
This is a hotfix for the android 2.7 release

2.7 Changelog:
- Added support for multiple days in the calendar view
- Added long-press to create time entries in the calendar view
- Added drag to edit time entries in the calendar view
- Improved editing flow in calendar view
- Improved autocomplete search when starting time entries
- Fixed night mode integration for devices that support it
- Fixed a crash that happened when selecting reports shortcuts
- Fixed several syncing issues
- Various UI/UX improvements
- Other stability and performance improvements

2.7.1 Additions:
- Fixed drawing behind navigation in the calendar view
- Fixed drawing behind navigation in the settings view
- Fixed a crash when starting time entries from the calendar
- Fixed a crash that happened when resuming the app after a long time in background

~2.7.1 long changelog (not acceptable in PlayStore):~
- ~Added support for multiple days in the calendar view~
- ~Added long-press to create time entries in the calendar view~
- ~Added drag to edit time entries in the calendar view~
- ~Improved editing flow in calendar view~
- ~Improved autocomplete search when starting time entries~
- ~Fixed night mode integration for devices that support it~
- ~Fixed a crash that happened when selecting reports shortcuts~
- ~Fixed several syncing issues~
- ~Fixed drawing behind navigation in the calendar view~
- ~Fixed drawing behind navigation in the settings view~
- ~Fixed a crash when starting time entries from the calendar~
- ~Fixed a crash that happened when resuming the app after a long time in background~
- ~Various UI/UX improvements~
- ~Other stability and performance improvements~

2.7.1 revised changelog (respecting the 500 characters limit):
- Improved editing flow in calendar view
- Improved autocomplete search when starting time entries
- Fixed night mode integration for devices that support it
- Fixed a crash that happened when selecting reports shortcuts
- Fixed several syncing issues
- Fixed drawing behind system navigation bars
- Fixed a crash when starting time entries from the calendar
- Fixed a crash that happened when resuming the app
- Various UI/UX improvements
- Other stability and performance improvements

### Relationships
Hotfix for #6561 

## Why do we want this?
Because we hate bugs, glitches and crashes

## How is it done?
🍒🍒⛏⛏

## :squid: Permissions
Merge only. I will do it.
Please don't forget to revert 96b0ea05f67e4d10fb7c4ea2e8379188ed400ecb before merging it into develop.

### CODE REVIEW

**Comment by heytherewill** [comment]
Changelog looks fine

**Comment by daividssilverio** [comment]
Oh... PlayStore has a hard limit of 500 characters... 2.7 update notes had exactly 500 characters 🤦‍♂

**Comment by daividssilverio** [comment]
Had to update the changelog due to limitations in the PlayStore release notes section:

- Improved editing flow in calendar view
- Improved autocomplete search when starting time entries
- Fixed night mode integration for devices that support it
- Fixed a crash that happened when selecting reports shortcuts
- Fixed several syncing issues
- Fixed drawing behind system navigation bars
- Fixed a crash when starting time entries from the calendar
- Fixed a crash that happened when resuming the app
- Various UI/UX improvements
- Other stability and performance improvements

**Comment by heytherewill** [comment]
Shorter version is also approved

**Pull request merged**
