### PR TITLE
Recolour the iOS app 

### PR DESCRIPTION
**Pull request by dshr**
## What's this?
This PR changes the main colours of the iOS app to match the new brand guidelines.

### Relationships
Closes nothing

## Why do we want this?
New branding, who dis?

## How is it done?
I changed some of the named colours, then some of the shared colours, and also had to replace a bunch of icons with hardcoded colours with tinted versions of them.

### Side effects
Sharp looks

## Review hints
Poke around the app, I guess. I did the whole pre-release checklist to see all the screens, and you can try that too. A little tip — cmd+shift+A toggles dark mode in the simulator

## :squid: Permissions
Only me and @heytherewill

### CODE REVIEW

**Comment by heytherewill** [comment]
Some of the plus icons are still green. They should all be pink

IMG_0004

IMG_0005
IMG_0008
IMG_0007
IMG_0006

**Comment by heytherewill** [comment]
The Stop button lacks an icon
IMG_0002

**Comment by heytherewill** [comment]
Other than that, everything looks good

**Comment by dshr** [comment]
@heytherewill addressed

**Pull request merged**
