### PR TITLE
Make premium Project features nullable and ignore in JSON.

### PR DESCRIPTION
**Pull request by kornelijepetak**
Make premium features nullable and ignore them when serializing in JSON.

Completes model part of #105

### CODE REVIEW

**Comment by willsb** [comment]
I don't think we can simply ignore then, can we? We should ignore based on whether the feature is available or not, right?

ping @arturs105 and @amulware

**Comment by amulware** [comment]
@willsb That's correct, and there is an issue for that. It requires workspace features, and some thinking, so no way we can do this right now. For the time being, I'm quite fine with ignoring the properties. I see no harm in that.

**Comment by amulware** [comment]
@willsb Does this work for you?

**Comment by willsb** [comment]
Since the issue is there to remind us, yeah, I guess it's fine. But I'm still a bit 🤔  over this

**Comment by amulware** [comment]
I understand. We'll have to think about this more, but for now, this makes things not break horribly.

**Pull request merged**
