### PR TITLE
Hook up daily tracked time label in calendar

### LINKED ISSUE #6368: Calendar: Fix total duration of TEs not working
Fix the total duration of the day's TEs.

### PR DESCRIPTION
**Pull request by arturs105**
## What's this?
This adds iOS parts for the daily tracked time.

### Relationships

Closes #6368

## How is it done?
Tried to do it the same way as Daivid did it for droid.

## :squid: Permissions
🦑

### CODE REVIEW

**Comment by sofokli1** [comment]
@arturs105 aren't changes in the firs 4 commits from Daivid already in the project branch?

**Comment by arturs105** [comment]
Yes, the changes from the first 4 commits are in the project branch. I started to work on this while Daivid's PR wasn't merged yet, so i branched off his branch no the project branch and i guess that's why those commits are there.

**Comment by sofokli1** [comment]
I would suggest to make a new branch with cherry picking your commit

**Comment by arturs105** [comment]
Closing this as #6464 is the same, but with no extra commits.

**Pull request closed without merging**
