### PR TITLE
Add Danger

### PR DESCRIPTION
**Pull request by khoi**
## What's this?
Introducing [Danger](https://danger.systems/ruby/) which is an attempt to automates

- PRs can be auto labelled with `ios`, `android`, `foundation` based on the changes commited. 
- Trivial code review. (missing DisposedBy, .Rx() on new line ...etc) **Will be implemented in a different PR**

The goal for this is so that we spend less time doing boring repetitive tasks, and focus on things that "spark joy" ™️. 

### Relationships
No issue created.

## Why do we want this?
Automation FTW.

### Side effects
- A new step to run `danger` will be added to CI.

## Review hints
- Read the rules defined in `Dangerfile`
- Creating commit that violates the rules.
- Push it up to this branch with the message contains "DISCARD" 
- Wait for CI to run and you should see that the PR's labels are added accordingly.

## :squid: Permissions
me

### CODE REVIEW

**Comment by kornelijepetak** [comment]
Who dat?! Where does this execute?

**Comment by khoi** [comment]
This will be executed in `bitrise` which I haven't added yet, waiting for @amulware's approval

**Comment by khoi** [comment]
right now you can it locally by
```
gem install bundler
bundle install
DANGER_GITHUB_API_TOKEN=YOUR_GITHUB_TOKEN bundle exec danger pr https://github.com/toggl/mobileapp/pull/4370 --verbose
```

**Comment by heytherewill** [comment]
Do you mind creating a step in bitrise that actually runs danger, for testing purposes?

Also, ping @amulware

**Comment by amulware** [comment]
Need to investigate before giving an answer. Putting it on my list.

**Comment by amulware** [comment]
We decided internally not to go ahead with this at the moment.

**Pull request closed without merging**
