### PR TITLE
📐 Rating ui padding

### LINKED ISSUE #2781: Rating UI: padding between the Rating card and Today section is too big
## 🐛 Bug Report
Padding should be 56pt but at the moment it's about 88pt.

Please, check the design: https://zpl.io/VDOWvzr

Build/Branch: Adhoc 1.8 (1617)
Phone OS: iOS 11
Phone model: iPhone6

### PR DESCRIPTION
**Pull request by khoi**
## What's this?
Make the rating UI more adaptive by letting Autolayout does it magic. Kudos to @dshr for the constraint bindings idea.

### Relationships
Closes #2781 

## How is it done?
Instead of using a fixed height like before, the CTA views are now anchored to the bottom of the CTAContainerView, which will make the container view adapt to the height of its subviews.

### Side effects
🤷🏻‍♂️

## :squid: Permissions
👨‍👩‍👧‍👧 anyone

### CODE REVIEW

**Comment by sofokli1** [comment]
Just for comparison (not in scale)

simulator | [zeplin link](https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5ae1d9897422687a8ba3b6a7)
------------ | -------------
simulator screen shot - iphone x - 2018-08-07 at 19 07 18 | screen shot 2018-08-07 at 19 15 52

**Comment by khoi** [comment]
I've decreased the top padding, let me know if this is ok @pe0ny 
screen shot 2018-08-08 at 4 03 26 pm

**Comment by pe0ny** [comment]
The top padding looks ok now. But as Eugene mentioned. Rating card's bottom padding (padding between the rating card and today section) seems definitely smaller compared to the designs. Can we increase it to 56 pt?

**Comment by khoi** [comment]
Final tweak which got approval from @pe0ny already :D screen shot 2018-08-09 at 1 14 00 pm

**Pull request merged**
