### PR TITLE
Move the eye icon into the password text field

### LINKED ISSUE #6239: Password suggestion in dark mode
When signing up, if the system fills the password with a suggested one, the field looks weird.

IMG_BA1634457DE1-1

This is true also for light mode, but it's not that bad.

IMG_2DC06417919A-1

### PR DESCRIPTION
**Pull request by simonrozsival**
## What's this?
This PR makes the "Strong Password" overlay of Autofill Password less glitchy.

### Relationships
Closes #6239 

## Why do we want this?
We want the UI to look nice.

## How is it done?
So far the button with the eye icon was placed on top of the password input view, now I changed it to be inside of the `rightView` subview (see https://developer.apple.com/documentation/uikit/uitextfield/1619596-rightview). The yellow overlay will therefore hide it, when it's shown.

### Side effects
This is not a side effect, but I'm still unable to fix the color of the password text in the dark mode. It still appears white on yellow, so it's practically "invisible".

## Review hints
Test this on your iPhone.

## :squid: Permissions
🦑

### CODE REVIEW

**Comment by simonrozsival** [comment]
I know that this PR doesn't make it beautiful and so it doesn't solve it 100%, on the other hand I don't think this issue has very high priority and that we shouldn't spend any more time on it.

**Comment by arturs105** [comment]
This breaks the reveal password button on iOS 11 - it is invisible, but tapping it still works though.

**Comment by simonrozsival** [comment]
Damn. It should work across all iOS supported versions (https://developer.apple.com/documentation/uikit/uitextfield/1619596-rightview). I'll look into it.

**Comment by simonrozsival** [comment]
@arturs105 I fixed the problem, I had to set the `Frame` correctly.

BTW this is what the yellow thing looks like now:
image
image

**Pull request merged**
