### PR TITLE
Add color binding

### PR DESCRIPTION
**Pull request by arturs105**

### CODE REVIEW

**Comment by willsb** [comment]
Why is this needed? You can simply use the included `MvxColorValueConverter` that's included with the plugin

**Comment by arturs105** [comment]
I did not know about that. So how would it be used to bind a view's background colour?

**Comment by willsb** [comment]
```
bindingSet.Bind(SomeView)
          .For(v => v.BackgroundColor)
          .To(vm => vm.SomeColor)
          .WithConvertion(colorConverter);
```

**Comment by arturs105** [comment]
🤦‍♂️ I forgot that bindings can be added for regular properties.

**Pull request closed without merging**
