### PR TITLE
Display integration test name on console

### PR DESCRIPTION
**Pull request by willsb**
Since integration tests are slow®, I added this as an indicator that something is happening. Will be very useful when the whole API is mapped and those tests begin taking a while to run.

Squash whenever.

### CODE REVIEW

**Comment by amulware** [comment]
Why are unrelated tests failing here?

**Comment by amulware** [comment]
Please mark PRs you are working on as `wip` to avoid unnecessary reviews.

**Comment by willsb** [comment]
This is not WIP

**Comment by amulware** [comment]
Where did 5eee765 come from then?

**Comment by willsb** [comment]
It addresses what we discussed in Nice, regarding displaying the time it takes for each test to run

**Comment by amulware** [comment]
There is a comment with a question above that has not been addressed.

**Comment by willsb** [comment]
This was not intentional and during the time refactor it was fixed. Please test it again :)

**Pull request merged**
