### PR TITLE
🌏 Allow using toggl.com credential in iOS's Autofill

### LINKED ISSUE #5207: Show toggl.com passwords in Apple Autofill
## 🐛 Bug Report
We've recently 🔥 1Password extension from our app in https://github.com/toggl/mobileapp/issues/5126 in favor of the native iOS Autofill.

However, in the current implementation, our website passwords are not suggested for the app.

## Expected behavior
If you have toggl.com password saved, it should be suggested.

### PR DESCRIPTION
**Pull request by khoi**
## What's this?
As the title says.

### Relationships
Closes #5207

## Why do we want this?
So Eugene can use his password without filtering.

## How is it done?
add toggl.com as associated domain following [Apple's instruction](https://developer.apple.com/documentation/security/password_autofill)

### Side effects
Nope.

## :squid: Permissions
🦑

### CODE REVIEW

**Comment by khoi** [comment]
Oops turned out the problem is that we didnt turn on associated domain in apple dev center. Its working now, try this build https://app.bitrise.io/artifact/16009243/p/39fba5bc62c5e21db6877a6d7029b7ec

**Comment by sofokli1** [comment]
Just tested your link, still the same

**Comment by sofokli1** [comment]
maybe someone else should test too, just in case

**Comment by khoi** [comment]
IMG_1510
hmm that's weird, can someone else try it, it's working on my device

**Pull request merged**
