### PR TITLE
Replace manual mode text

### LINKED ISSUE #3672: Improve UX for changing manual/timer modes
### Current state of affairs

Users can currently switch between manual and timer tracking modes in the settings. This will change the default behavior of the ➡️button in the Main Log. However, they can execute the Start in the other mode by long pressing the ➡️button. 

The problem is... many users are not really aware of this.

### Suggestions

We could improve the description in the settings, to include something like: 
> This option sets the default behavior for the start button. Regardless of the current option, long pressing the button will always activate the alternative mode.

We need a better copy, but something along those lines.

The alternative would be to use the new onboarding step, but it may be an overkill at this point. And if you think the long description would clutter the settings too much, we could maybe remove the description (or shorten it) once the user has used the long press once or twice (or whatever). Or not.

### PR DESCRIPTION
**Pull request by Odrakir**
## What's this?
Changes the text for the manual mode switch in settings

I did change the text to make it a little shorter from:

> This option sets the default behavior for the start button. Regardless of the current option, long pressing the button will always activate the alternative mode.

to

> Sets the default behavior for the start button. Long pressing the button will always activate the alternative mode.

Let me know if that's ok, maybe @toggl/androids should change it too.

### Relationships
Closes #3672 

Unless @amulware says we should change the start button UI in this same PR (otherwise I'll create another issue)

## Why do we want this?
This is very straight forward.

## :squid: Permissions
Wait for @amulware

### CODE REVIEW

**Comment by amulware** [comment]
Why do we want this though? It's not clear to me from the issue.

**Comment by Odrakir** [comment]
🤔 Why do we want what? The text? As described in the issue this is so the long-press thing is a little bit clearer. We are taking the same approach as Android did. I still thing this is not enough and we should do something in the button itself.

**Comment by amulware** [comment]
I mean: The text was already changed - why are we changing it again to a shorter version?

**Comment by amulware** [comment]
No wait.. the text was not changed yet? I thought it was... My bad. Why did you go with this shorter version though?

**Comment by Odrakir** [comment]
I merely took out the redundant parts to make it shorter. I just seen you had posted another version in the issue, maybe I can use that one instead. Or maybe we could ask @maritoggl to give us the definitive one.

**Comment by amulware** [comment]
I thought about it and I think I prefer your option. It might be clearer, being shorter, and it contains the same information.

**Comment by amulware** [comment]
The same string should be used by Android right? Or do we need to do something separately there? If so, please make sure that happens. :)

**Comment by Odrakir** [comment]
Judging by #3672 Android is not using the Resources file for this (and many other texts, apparently). They should, right?

Also... What happens with the animation? Should I create another issue?

**Comment by amulware** [comment]
I'd check with @daividssilverio on what Android is doing, especially now with the i18n project changing a lot. But I see now that the previous pull request only changed it on Android then. This should really be simpler then, I hope it is with the i18n changes.

And yes, if you close the issue, please create follow ups (one per platform) about the animation, and link this thread where it's being discussed: https://toggl.slack.com/archives/CMB9FDE5D/p1565778022020100

**Comment by maritoggl** [comment]
> I merely took out the redundant parts to make it shorter. I just seen you had posted another version in the issue, maybe I can use that one instead. Or maybe we could ask @maritoggl to give us the definitive one.

The one you proposed is good 👍

**Comment by daividssilverio** [comment]
Hey y'all, both droid and iOS should use only `Resources.resx` defined string, unless ofc it's a platform limitation on specific use case. Either way, every text entry should be at least present in the `Resources.resx` so that it can be translated.

**Comment by Odrakir** [comment]
So #5678 should be changed, right?

**Comment by daividssilverio** [comment]
Yeah, and #5747 actually changed it already.

**Pull request merged**
