### PR TITLE
Giskard 1.5.2 - Sodium Hotfix 2

### PR DESCRIPTION
**Pull request by daividssilverio**
## Changelog
```
- Added UNDO feature after deleting time entries by swiping
- Added notifications for idle and running time entry (enable in settings)
- Added in-app feedback form (let us know what you think!)
- Added workspace selection to Reports screen
- Added warning when user does not belong to any workspace

- Improved syncing process
- Improved application behaviour on slower networks
- Improved performance and stability
- Improved onboarding hints
- Improved the way unsyncable time entries are visualized

- Fixed application freezes when interacting with persistent notifications (running/idle)
- Prevented auto log in with previous user on reinstall
- Fixed notifications so that they no longer emit sounds
- Various other bug fixes

Hotfixes:
- Fix lollipop devices startup crash
- Fix time entries sections headers
- Fixed bug that crashed the application in main view
```

## History of changes:
Sodium - Sodium Hotfix #2
https://github.com/toggl/mobileapp/compare/sodium...sodium-hotfix-2

1.5.1 - Sodium Hotfix #2
https://github.com/toggl/mobileapp/compare/giskard-1.5.1...sodium-hotfix-2

## :squid: Permissions
@kornelijepetak or @willsb

### CODE REVIEW

**Comment by willsb** [comment]
Please add the entire changelog from 1.5.1 to this release as well

**Comment by kornelijepetak** [comment]
Please create a release here as well:
https://github.com/toggl/mobileapp/releases

**Comment by daividssilverio** [comment]
@kornelijepetak I'll do as soon as the fixes are merged into this PR.

**Comment by daividssilverio** [comment]
ref #3344 -> cherry pick of #3331

**Comment by daividssilverio** [comment]
ref #3365 -> cherry pick of #3285

**Comment by kornelijepetak** [comment]
Released to 100% of users.

**Pull request merged**
