### PR TITLE
Remove certificate override

### LINKED ISSUE #604: Fix certificate trust issue on iOS 11
Right now we are ignoring the certificates altogether, but we need to investigate, find out what's causing the problem and provide an appropriate solution for the problem.

### PR DESCRIPTION
**Pull request by willsb**
Closes #604 

Latest Stable has the fix. Before merging, we need to figure out how to install and trust the certificate using Bitrise, otherwise UI tests will go :boom: 

 🦑

### CODE REVIEW

**Comment by willsb** [comment]
The other places where it happens are all in test code. To🔥those we'd need to automate the installation of certificates on Desktop 🤷

**Comment by simonrozsival** [comment]
OK then.

**Comment by amulware** [comment]
I'm fine with this, but as you say, please figure out bitrise first. :)

**Comment by amulware** [comment]
On hold for the time being. More info at some point down the line.

**Comment by amulware** [comment]
Closing this until we actually fix bitrise accordingly.

**Pull request closed without merging**
