### PR TITLE
Add droid calendar swipe to change day

### LINKED ISSUE #5863: Calendar: Support changing date by swiping
Ability to swipe left and right to move a single day back and forth

your mission should you choose to accept, will be:
- [x] add ability to swipe left and right
- [x] add needed VM logic (be aware that will be used by android too so feel free to talk with your project members dev if in doubt when implementing)
- [x] make sure it can only swipe for 2 weeks (starting from today and back). it should just bounce when trying to swipe to a date outside the 2 weeks range.
- [x] make sure it works on iPad
- [x] make sure there is enough VM logic so that the weekly date picker can be updated based on the swipe of the main VM and back (this is optional in order to complete this issue since it will be worked again in #5865 )

Feel free to copy this list in the PR so that the reviewer knows what to check

### LINKED ISSUE #5864: Calendar: Support changing date by swiping
Ability to swipe left and right to move a single day back and forth

### PR DESCRIPTION
**Pull request by daividssilverio**
## What's this?
This makes the calendar tab fragment a view pager for calendar days.

### Relationships
Closes #5864  

## How is it done?
With a view pager and some relays.

### Why not another way?
Feel free to suggest something different.
I thought about using a raw `PagerAdapter` and handle `CalendarDayView`s directly... but the `FragmentStatePagerAdapter` worked well... so I just used it.

## Review hints
None this time.

## :squid: Permissions
🦑 it 📆 team

### CODE REVIEW

**Comment by semanticer** [comment]
Clicking on a calendar tab moves me to the current time right? But maybe it should also move the page to the current date? At least that's what I would expect as a user.

**Comment by semanticer** [comment]
It's very easy to move back accidentally instead of moving between days with the new Android 10 gesture navigation but I guess there is nothing we can do about that.

**Comment by semanticer** [comment]
Maybe you should consider new ViewPager2 - https://medium.com/google-developer-experts/exploring-the-view-pager-2-86dbce06ff71 https://developer.android.com/jetpack/androidx/releases/viewpager2#1.0.0-beta04

Oh no wait - it's probably only for Androidx 🤦‍♂

**Comment by sofokli1** [comment]
I think the issues this closes is for iOS (and it closed already), I think it should be #5864

**Comment by daividssilverio** [comment]
> I think the issues this closes is for iOS (and it closed already), I think it should be #5864

Thanks.

**Comment by daividssilverio** [comment]
> As I mentioned above, I don't think the current calendar tab click behavior is correct. I'm also not sure if we should display the line with current time in all of the pages - I would prefer it only on today's page.

Let's just confirm that with @maritoggl . The change is trivial.

> The interactions like creating a new event by clicking into calendar view don't work for me - but I guess that's not the point of this PR and you are in the middle of polishing these things?

There's an issue for that, which will work nicer when we finish the contextual menu as well #5868 
 
> Given that we probably can't use the new viewPager2 (maybe with reverse jetifier?) the code looks fine.

Oh man... you make me dream, I'll take a look.

**Comment by daividssilverio** [comment]
> Given that we probably can't use the new viewPager2 (maybe with reverse jetifier?) the code looks fine.
> Oh man... you make me dream, I'll take a look.

@semanticer as far as I checked, maybe not for now. We can revisit all the view pagers in the app later when we move to androidX as well.

**Comment by daividssilverio** [comment]
@semanticer 
>It's very easy to move back accidentally instead of moving between days with the new Android 10 gesture navigation but I guess there is nothing we can do about that.

We can opt-out for navigation gestures while in this lab when we update our stack to use Xamarin 10. But that should be done first in develop, then merged back into the project branch to then be fixed. I'll create an issue for that.

**Pull request merged**
