### PR TITLE
Use string resources for day names and initials

### PR DESCRIPTION
**Pull request by arturs105**
## What's this?
This PR makes sure we use our string resources for day names and initials.

### Relationships
Ref #5999 (specifically this [change](https://github.com/toggl/mobileapp/pull/5999#discussion_r343637352) request)

## Why do we want this?
For localisation purposes.

## :squid: Permissions
🦑

### CODE REVIEW

**Comment by sofokli1** [comment]
he beat me to the review 😄

**Comment by arturs105** [comment]
Damn these race conditions 😄

**Comment by sofokli1** [comment]
@heytherewill are you ok with the latests changes here?

**Comment by sofokli1** [comment]
@heytherewill in case you have an issue with this let us know and we can make an other PR

**Pull request merged**
