### PR TITLE
Add select country UI tests

### LINKED ISSUE #3861: Test Country Selection in Signup:
Add test that tests country selection on signup page.
Will need to
-Navigate to signup page
-Test country selection by selecting country (this can be typed)
-Test back button to exit country selection
-Do both return to signup page with correct country selected? (Is it even possible to check this)

### PR DESCRIPTION
**Pull request by daividssilverio**
## What's this?
This add UI tests for the country selection screen/modal.

### Relationships
Closes #3861 #4154

## Why do we want this?
So we can run automated UI testing o/

## How is it done?
I had to change a bit `WaitForElementWithText` for iOS because the testing framework didn't find the text inside UIButton itself, apparently, there's a UILabel inside the UIButton and Xamarin.Tests.UI does not consider the text on it the text of the button itself 🤔 

### Why not another way?
🤷‍♂️ Suggestions are welcome.

### Side effects
More UI tests.

## Review hints
Run the tests on both Android and iOS.

## :squid: Permissions
🦑 after at least one person from @toggl/ios-senseis reviews it, there's no changes to Android, but I did touch a few `xib`s.

### CODE REVIEW

**Comment by Odrakir** [comment]
Is this PR still a thing?

**Comment by heytherewill** [comment]
ping @daividssilverio to know if this is still a thing

**Comment by daividssilverio** [comment]
This was working when I finished my UI Test week. Could the current UI test weeker take ownership of this PR? @heytherewill ?

**Comment by simonrozsival** [comment]
If there is some development with this PR while I'm on vacation, please don't wait for my approval.

**Comment by khoi** [comment]
i'm taking over this issue if you don't mind @daividssilverio

**Pull request merged**
