### PR TITLE
Release 1.3 - Saturn

### PR DESCRIPTION
**Pull request by amulware**
:shipit: 🚀  ☀️  

```
- Added manual mode
- Added time edit wheel
- Added in-app feedback function
- Added 'today' and 'yesterday' shortcuts to reports calendar
- Added password validation during signup

- Fixed input bugs with some Asian language keyboards
- Fixed crashes and empty log that could happen when tapping start/stop/continue buttons multiple times quickly
- Fixed ignoring local time zones for date display
- Fixed syncing bar sometimes displaying wrong state when offline
- Fixed leak that could cause the app to use more battery than needed

- Various other fixes and improvements
```

### CODE REVIEW

**Comment by amulware** [comment]
Added changelog.

**Comment by amulware** [comment]
Triggered first RC.

**Comment by amulware** [comment]
Ready for merging 🚫 🦑

**Comment by luiscruz** [comment]
Hi @amulware and @simonrozsival 
Could you explain what was the issue that was causing the app to use more battery than needed? (sorry for the invasion)

**Comment by amulware** [comment]
@luiscruz No problem. We had a somewhat complex animation powered by UIDynamics that wasn't cleaned up properly, so it would keep simulating that even if not visible. The relevant changes happened here: #1418

**Comment by luiscruz** [comment]
Thanks a lot @amulware!
(This is helpful for a work I'm currently doing — https://tqrg.github.io/energy-patterns/)

**Pull request merged**
