### PR TITLE
Fix main view for iOS 10

### PR DESCRIPTION
**Pull request by arturs105**
**Previously:** 
img_1166

**Currently:** 
screen shot 2018-03-14 at 10 41 53

❗️  Please do a functional test.

### CODE REVIEW

**Comment by simonrozsival** [comment]
This probably closes https://github.com/toggl/mobileapp/issues/1680

**Comment by simonrozsival** [comment]
Also shouldn’t this be merged rather into the hotfix branch so we could ship it asap?

**Comment by arturs105** [comment]
Yes, yes it could. Do you mean `1.4.1`?

**Comment by simonrozsival** [comment]
Yes, exactly. Does @amulware agree?

**Comment by amulware** [comment]
He does.

**Pull request closed without merging**
