### PR TITLE
Add Timeline view model

### PR DESCRIPTION
**Pull request by arturs105**

### CODE REVIEW

**Comment by willsb** [comment]
I'm putting this on-hold until our discussion Monday Morning

**Comment by willsb** [comment]
Given our discussion yesterday, this should instead:

- Fetch data in the last month
- Merge it with the project cache
- Transform it into a lightweight model that can be used by the timeline
- Expose a property that represents the visible time frame

Since we don't have the project cache thingy, I'd use this PR to add both the ViewModel and the View to the project without much code. If you don't wanna do this, please put it back on hold until the Project cache is implemented.

**Comment by arturs105** [comment]
Wasn't it a week not a month?

**Comment by willsb** [comment]
Yeah, it's a month, my bad 😄

**Comment by arturs105** [comment]
Putting on hold until project cache is ready.

**Comment by willsb** [comment]
The `.csproj` in this one is a mess. I'd rather manually copy the few file changes and create a new PR instead.

**Comment by willsb** [comment]
I vote for 🔥 this PR, specially since timeline won't happen for first beta.

**Comment by amulware** [comment]
Closing this since we removed it from our current plans.

**Pull request closed without merging**
