### PR TITLE
Remove decorators from sync

### PR DESCRIPTION
**Pull request by simonrozsival**
There are now no more decorators so @amulware should be happy now 😄 

Squash whenever

### CODE REVIEW

**Comment by amulware** [comment]
I cannot be bothered to review all that setup code. Let's merge the diagram drawer first, and then we can just create an image for this.

**Comment by simonrozsival** [comment]
Here is the generated graph for pull sync:

[sync-graph-pull.pdf](https://github.com/toggl/mobileapp/files/2158851/sync-graph-pull.pdf)

**Comment by juanlaube** [comment]
Looks good! The graph saves a lot of time 😄

**Comment by amulware** [comment]
I need a bigger screen.

**Comment by amulware** [comment]
Have there been no changes to the push-graph? The pull-graph looks good from the diagram. :)

**Pull request merged**
