### PR TITLE
Fix help button

### PR DESCRIPTION
**Pull request by willsb**
It wasn’t working on iOS. Now it is :)

Squash whenever

### CODE REVIEW

**Comment by amulware** [comment]
Do not squash this into neptune. That branch is frozen. There will be another one for 1.7.1 soon.

**Comment by amulware** [comment]
Rebase against hotfix branch please. :)

**Comment by simonrozsival** [comment]
We should carefully check if we didn't forget anything else during the #2436 as the version number was incorrect as well (#2525).

**Comment by arturs105** [comment]
I think this closes #2509

**Pull request merged**
