### PR TITLE
Remove model generators

### PR DESCRIPTION
**Pull request by Odrakir**
In order to refactor the models (#1681), we are going to delete the code generators first. (hopefully forever 🤞 )

### CODE REVIEW

**Comment by amulware** [comment]
I want all the requested, and at least one more our of { @kornelijepetak, @arturs105, @juanlaube } (my estimate of who has worked with this stuff the most, but other's are welcome to comment, obviously).

If there are concerns about this, speak up!

**Comment by juanlaube** [comment]
I don't like the `.tt` templates, so I'm more than ok with this. That being said, I'm wondering if we don't introduce a bug in the future because we forget to add/remove things in the constructors 🤔

**Comment by amulware** [comment]
Updated original message to mention #1891.

**Comment by Odrakir** [comment]
That's for another PR, @kornelijepetak. I'm on it.

**Comment by willsb** [comment]
I'm pro removing the generators, but this PR *does not* close #1891. It only burns files without proposing what's the solution.

**Comment by Odrakir** [comment]
Are you sure you are ok with this 😀

As I said, improvements come in another PR. I told @amulware this would happen, but we agreed on doing it in separate PRs to simplify reviews.

**Comment by willsb** [comment]
Again, if the solution comes in another PR, how does this close the issue?

Either change the description or propose the changes you are going to do here.

**Comment by Odrakir** [comment]
Oh! Doh...

Sorry, a lot on my plate lately.

**Pull request merged**
