### PR TITLE
Add google signup

### LINKED ISSUE #862: Google sign up
Allow sign up with Google and show 'Sign up with Google' at the bottom of the sign up screen. Show this both in email and password state.

Zeplin: https://zpl.io/bzwL6Y4

toggl - ios - sign up step1 1x

### PR DESCRIPTION
**Pull request by willsb**
Closes #862 

Blocked by https://github.com/toggl/backend/issues/5901

Squash, but only once the fix for the above is into production.

### CODE REVIEW

**Comment by amulware** [comment]
The backend issue is closed. Let's revisit this.

**Comment by willsb** [comment]
This is ready for reviews and, more importantly, for functional tests

**Comment by simonrozsival** [comment]
I created a new issue for the integration tests (#1239) so we can merge this.

**Comment by willsb** [comment]
Formally requesting @simonrozsival to re-review this, as some conflicts were fixed during the merge

**Comment by simonrozsival** [comment]
I don't think any of the conflicts could have any impact on the functionality.

**Pull request merged**
