### PR TITLE
Rebranding announcement popups

### LINKED ISSUE #7689: August 2020 Rebranding Popup
## 🎯 What needs to be done?
We want to add a relatively simple popup for the upcoming rebranding of Toggl.

It is quite similar (but even simpler) to the thing we did for January promo, which is detailed in [this issue](https://github.com/toggl/mobileapp/issues/6616).

## 📝 Detailed explanation
We're doing this to announce the transition of Toggl to Toggl Track, but also to mention our other apps + Toggl Plan & Toggl Hire.

- [Slack Thread in Mobile team about this](https://toggl.slack.com/archives/C02APMYTM/p1596806112129400)

**UPDATE** 

If possible, Marketing would appreciate 2 notifications - one for prelaunch and one for when the rebrand is live.

More info about it [is here](https://www.notion.so/toggl/customer-email-sends-in-app-announcements-rebrand-coming-soon-3cdbbcde0f1c4a1ab89d4a568d6d0643#aee36ec018e143a18082069fa3f07817) (Notion)

If not, I’ll edit this issue again to just leave the preferred option.

**Pre-launch**
Timing: Should start on **August 31** and last until **September 6**
Link: http://support.toggl.com/en/articles/4338240-frequently-asked-questions-toggl-track-toggl-plan-and-toggl-hire 
(KB Article)
To whom should it show: Anybody who opens the app during this time (BUT to be shown only once!)

**Live**
Timing: Should start on **September 7th** and last until **September 14th**
Link: https://toggl.com/blog/toggl-rebrand-toggltrack (Blog Post)
To whom should it show: Anybody who opens the app during this time (BUT to be shown only once!) 

Not sure if we should try the pop-up activation via Firebase, but if it adds to the complexity I guess we should skip due to time constraints.

_I’m waiting on pre-defined links for KB & Blog Post that you can use even though they aren’t live, will update as soon as I get them._

## 🎨 Graphical resources

Link to **Pre-launch** graphics
https://app.zeplin.io/project/5b9f4b52a7b6df68f4c212dc/dashboard?seid=5f2d47e36aa8ce27ab025278

Link to **Live** graphics
https://app.zeplin.io/project/5b9f4b52a7b6df68f4c212dc/dashboard?seid=5f3121917948241d309291fd

Both have designs for iOS & Android, Light & Dark.

_If there are any issues with the length of copy, design or anything, do ping me, I'll try to fix it asap!_

## 🛠 Technical remarks
Not sure if there's anything special to mention. For the January campaign that utilized similar popups, we added an A/B test and Firebase remote config, which shouldn't be needed here. 

Notes from Paul in [this Slack thread](https://toggl.slack.com/archives/C0170MEUGJV/p1596628094055000?thread_ts=1595944193.023500&cid=C0170MEUGJV):

> I don't see a/b/firebase being needed at all
> just show it the first time when running version X
> and then we remove it in version Y again

_Actually, Firebase remote config might be useful because of the weird timings of the 2 pop-ups, but we could probably go without it too._

## 🔗 Dependencies
- New App Store build ready with new screens & ASO (Aleks)

## 🖼 Express your sentiment towards the issue
[Eh 🤷‍♂️](https://media.giphy.com/media/JRhS6WoswF8FxE0g2R/giphy.gif)

### PR DESCRIPTION
**Pull request by heytherewill**
## What's this?
This adds the popups to let the users know about the rebranding

### Relationships
Closes #7689

## Why do we want this?
Rebranding

## How is it done?
This is inspired by https://github.com/toggl/mobileapp/pull/6640, but it's a lot simpler

## Review hints
You can change device time or change the time in the code to range from yesterday to today; doesn't matter, just make sure that this popup will only trigger once

## Localizations
We chose not to translate this copy, but it will appear to all users nonetheless

## :squid: Permissions
Only myself

### CODE REVIEW

**Comment by sofokli1** [comment]
looks like navigation fails to find a presenter for the view

**Comment by simonrozsival** [comment]
☝️ yep, iOS doesn't show the popup

**Comment by heytherewill** [comment]
I haven't implemented it on iOS yet, guys 🙈

**Comment by simonrozsival** [comment]
The browser window opens correctly, the web pages aren't shown correctly, but I assume that's because they're hidden at the moment.

**Pull request merged**
