### PR TITLE
Fix a cast which causes InvalidCastException

### PR DESCRIPTION
**Pull request by simonrozsival**
Sync does not work right now. This fixes it. Ref #724.

Squash whenever.

### CODE REVIEW

**Comment by amulware** [comment]
What exactly was the problem?

**Comment by simonrozsival** [comment]
Line 98 throws.

**Comment by amulware** [comment]
Could this alternatively be fixed by adding an `out` to the interface's generic parameter?

**Comment by simonrozsival** [comment]
I think the casts between `TModel` and `TRealmEntity` are now justifiable because they only happen in the private methods and we know exactly what type is in each field.

**Comment by amulware** [comment]
One thing I note though: We didn't notice this failing before. Is this entirely because we do not have tests for realm? If so... not much we can do right now, but still, dangerous.

**Comment by simonrozsival** [comment]
We don't have tests for RealmAdapter. In fact I don't know how that would be possible to do. We discussed it with @willsb and there is some way of doing integration tests for realm but we haven't done it yet.

This bug was introduced yesterday in #724, I did a poor job of testing the PR's functionality in the simulator - the sync indicator shows success, but it is a lie.

I am happy with this fix, so I will squash it.

**Pull request merged**
