### PR TITLE
Implement calendar contextual menu on iOS

### LINKED ISSUE #5870: Calendar: Add contextual menu
For all contextual menus, if the user taps outside the the contextual menu should shake (this is to show the user that it needs to make a decision in order to dismiss it). There is one exception to the above and that is for the situations where the user drags a TE start, stop or the whole thing (only for the one that is in focus in the contextual menu).

Ideally we want the start and end time that is shown in the contextual menus (where it applies) to update when the user drags the handles of the TE or the whole TE. If this is hard to manage please let me know so that we can act accordingly.

### Newly created TE contextual menu (triggered when creating a TE with long press)
- [x] Discard (deletes the TE)
- [x] Edit (opens edit view)
- [x] Save

- [x] New `CalendarNewTimeEntryCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `Discard`
    - `Edit`
    - `Save`

Design: https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5d88b3c9f1714261f39bed5a

### Existing TE contextual menu (triggered when tapping on an existing TE)
- [x] Delete
- [x] Edit (open edit view)
- [x] Save (to save changes when dragging the handles or the whole view)
- [x] Continue (starts a new TE with same metadata project, tags, etc at current time. Same as in main log)

- [x] New `CalendarExistingTimeEntryCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `Delete`
    - `Edit`
    - `Save`
    - `Continue`

Design: https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5d88b3c87f3832659d6c4e47

### Running TE contextual menu (triggered when tapping on a running TE)
- [x] Discard (deletes the TE)
- [x] Edit (opens the running TE edit view)
- [x] Save (to save changes when dragging the handle on top)
- [x] Stop (stops the running TE)

- [x] New `CalendarRunningTimeEntryCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `Discard`
    - `Edit`
    - `Stop`
    - `Save`

Design: https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5d88b3c900b356612bf9293f

### Calendar event contextual menu (triggered when tapping on a calendar event)
- [x] Copy as Time Entry (creates a TE with start and end set and the description of the calendar event)
- [x] Start (Creates a Running TE that starts at current time and has the same description as the calendar event)

- [x] New `CalendarEventCM` event with 1 parameters (triggered either when the contextual menu is dismissed or when one of the options is tapped)
- `SelectedOption` string with values from the following list
    - `Dismiss` (this is for the x button interaction)
    - `CopyAsTimeEntry`
    - `Star`

Design: https://app.zeplin.io/project/5728ce853dd1b182475f25e9/screen/5d88b3c94aa1d6182bce2c12

### LINKED ISSUE #6371: Closing the contextual menu for a calendar event crashes the app
Depends on #6340

## To reproduce
1. Tap on a calendar event to open the contextual menu
2. Tap on the "x" button to close the menu
3. 💥

### LINKED ISSUE #6373: Drag handles remain on a time entry after tapping on a calendar event
## Expected behaviour
The drag handles should disappear after tapping on any other item in the calendar.

## To reproduce
1. Open the calendar view
2. Tap on a time entry
3. Now tap on a calendar event in the same day
4. The previously tapped time entry still has the drag handles

### PR DESCRIPTION
**Pull request by arturs105**
## What's this?
This PR adds the iOS parts of the contextual menu.

### Relationships

Closes #5870 
Closes #6371
Closes #6373

## How is it done?
giphy

### Why not another way?
'Tis the best way!

### Side effects
🤷‍♂ 

## :squid: Permissions
🦑

### CODE REVIEW

**Comment by daividssilverio** [comment]
Some more bugs:
- When you click on running time entry, discard  or change the selected item, the running time entry appearance changes as it was stopped, but it actually didn't.
- when☝️ happens, you can actually change the running time entry offset as well. Saving it causes the time entry to be stopped.

**Comment by arturs105** [comment]
> 1. Changes made to an item are not discarded when you select a new item, the bottom sheet comes up and you select "discard changed".

Done

> 2. The "discard changes bottom sheet" doesn't appear when you click outside of an item.

Tapping outside to dismiss is a feature not implemented yet. Also: we're past the implementation phase, so this feature might be dropped or implemented later.

> 3. When you select a new item to edit after making changes, select "keep editing", the handles stay on the newly selected item instead of going back to the old item.

Done

> 4. When you change between items during edition, even after selecting "discard changes", the changes made during drag to edit are committed anyway.

Done

> 5. When you click on running time entry, discard or change the selected item, the running time entry appearance changes as it was stopped, but it actually didn't.

Done

**Comment by daividssilverio** [comment]
> Changes made to an item are not discarded when you select a new item, the bottom sheet comes up and you select "discard changed".

Done -> 👍 

> The "discard changes bottom sheet" doesn't appear when you click outside of an item.

Tapping outside to dismiss is a feature not implemented yet. Also: we're past the implementation phase, so this feature might be dropped or implemented later. -> 👍 ➿ @sofokli1 

> When you select a new item to edit after making changes, select "keep editing", the handles stay on the newly selected item instead of going back to the old item.

Done -> :x: It still happens when you switch between time entries and calendar events.

> When you change between items during edition, even after selecting "discard changes", the changes made during drag to edit are committed anyway.

Done -> 👍 

> When you click on running time entry, discard or change the selected item, the running time entry appearance changes as it was stopped, but it actually didn't.

Done -> 👍

**Comment by daividssilverio** [comment]
@arturs105 
Something else I've noticed is that the long press to start a manual time entry actually creates a time entry right away and doesn't trigger the "new time entry contextual menu", which lets you drag to edit before saving.

**Pull request merged**
