### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by juanlaube**
Hey VS, it's should be your job to do this, but no... :unamused:

Requires EditorConfig extension in VS4Mac

### CODE REVIEW

**Comment by amulware** [comment]
Also include a new line at the end of the file please. :P

**Comment by amulware** [comment]
(The assignment was by mistake, meant to self-request review)

**Comment by simonrozsival** [comment]
Please add `end_of_line` as @kornelijepetak suggested 👍

**Comment by juanlaube** [comment]
I think we can also add `trim_trailing_whitespace` and `insert_final_newline`. What do you think @kornelijepetak @simonrozsival @amulware?

**Comment by juanlaube** [comment]
Most editors support this, either included as part of the editor or through some kind of extension. I doubt there's any modern editor/IDE that doesn't support this.

**Pull request merged**
