### PR TITLE
Jupiter Hotfix #2 - 1.4.2

### PR DESCRIPTION
**Pull request by amulware**
Changelog:
```
- Fixes tags not copying when continuing a time entry sometimes
- Fixed crash when using password manager to login
- Improved stability of loading time entries
```

### CODE REVIEW

**Comment by amulware** [comment]
I just released this. Still gotta fix those conflicts and then it's squishidysquash 🦑

**Comment by amulware** [comment]
I hereby grant permission to @willsb of 🇧🇷 to resolve these conflicts, because they scare me.

**Comment by willsb** [comment]
This is now review-ready

**Comment by amulware** [comment]
I'd accept it if I could. :trollface: 
Whenever someone else does, feel free to merge (no squash!)

**Pull request merged**
