### PR TITLE
Sanic tapes: Main log create/bind ViewHolders

### LINKED ISSUE #3517: Trace main recycler adapter ViewHolders creation/binding
Trace the main recycler adapter creation/binding of view holders.
- [x] MainLogCellViewHolder
- [x] MainLogSectionViewHolder
- [x] MainLogSuggestionsListViewHolder

### PR DESCRIPTION
**Pull request by daividssilverio**
## What's this?
This adds traces in the main recycler adapter to trace creation and bindings of view holders.

### Relationships
Part of #3400 
Closes #3517 

## Why do we want this?
Gotta know how fast/slow the main recycler is.

## How is it done?
I've added traces for all creations and binds with basic sampling logic. 
100% of view holders creations are traced.
10% of the item view binds are traced.
50% of the section view binds are traced.

### Why not another way?
This is android specific, so there's no point in measuring from the ViewModel. And I rather not add a property in the ViewModel to get the singleton stopwatch provider since it won't matter in the end.

### Side effects
This will slightly reduce performance in the main log. Sampling should help reduce that.

## Review hints
Review by commit could help. But the changes are really small.

## :squid: Permissions
:sanic: squad. 🦑 please

### CODE REVIEW

**Comment by daividssilverio** [comment]
Tests.Unit.Split: https://app.bitrise.io/build/e1d900e1dac47ed6
Tests.AppBuilds.iOS: https://app.bitrise.io/build/4913d6b5416b2190
Tests.AppBuilds.Android: https://app.bitrise.io/build/dae41d508957b657

**Comment by willsb** [comment]
Did you measure the impact of this in the rendering? Are the sample percentages entirely empirical?

**Comment by daividssilverio** [comment]
I did not measure the tracing specifically. I did see the result of adding simple traces around when measuring performance with Android Studio tracing tool. Every trace adds a few microseconds, depending on the device.

Sampling percentages are entirely empirical.

**Comment by daividssilverio** [comment]
Rerun on bitrise: https://app.bitrise.io/build/7c92513c54c250f5

**Pull request merged**
