### PR TITLE
Remove MvvmCross from namespaces

### LINKED ISSUE #4849: Rename Toggl.Foundation.MvvmCross to Toggl.Foundation.UI
⚠️ **This needs to be done before the project starts. It is basically a VisualStudioRefactorTools-Fu showoff, but since it touches a lot of files I would rather have this on develop ASAP.** ⚠️ 

- [x] Rename the project to `Toggl.Foundation.UI`
- [x] Change all namespaces in the project to `Toggl.Foundation.UI.*`
- [x] Change the project's default namespace to `Toggl.Foundation.UI`
- [x] Mass replace all instances of `using Toggl.Foundation.MvvmCross` as well
- [x] Rename the MvvmCross folder inside `Toggl.Foundation.Tests` to `UI`
- [x] Change all namespaces inside that folder to `Toggl.Foundation.Tests.UI`

### PR DESCRIPTION
**Pull request by heytherewill**
## What's this?
This removes the existence of MvvmCross from our namespaces

### Relationships
Closes #4849

## Why do we want this?
Mvexit

### Side effects
History 🅱️roke on GitHub

We can install [this extension](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) to make it work again or use `$ git log --follow path/to/file.cs` if your favorite browser does not support extensions

## Review hints
Per commit

## :squid: Permissions
Me

### CODE REVIEW

**Comment by amulware** [comment]
"History might be funny :/" is not good enough to get my approval.

**Comment by heytherewill** [comment]
This is a draft PR, you shouldn't be reviewing it 😄

**Comment by daividssilverio** [comment]
The history looks alright, will it mess things up for realses?

**Comment by heytherewill** [comment]
I am closing this in favor of the mass rename proposal

**Pull request closed without merging**
