### PR TITLE
Preserve Ultrawave models

### PR DESCRIPTION
**Pull request by willsb**
The models here are needed for every client, but they get stripped away by the linker because there are no direct references to their constructors. The `PreserveAttribute` makes the linker ignore the class and its members when stripping code.

Squash whenever

### CODE REVIEW

**Comment by amulware** [comment]
How come these models aren't generated?

**Comment by willsb** [comment]
We might need to do a lot of annotation on those models because of serialization

**Comment by amulware** [comment]
Right.

**Comment by amulware** [comment]
Thing is, this will not be needed, once we fix #100. Is this still worth merging?

**Comment by willsb** [comment]
I don't think the model generation should apply Ultrawave. The models are very tailored for our needs (specially because of annotations due to, say, backend weirdly naming fields or ignore-on-serialize rules).

>Is this still worth merging?
The app literally can't (de)serialize anything without merging this, so yes, there's value

**Comment by amulware** [comment]
I'm not sure what you are talking about. With #100, the model classes will be explicitly mentioned in code. Should that not prevent them from being removed?

Also, I'm not arguing for generation in any way, your comment about annotation is valid.

**Comment by willsb** [comment]
Oh, I see your point. I thought you were still defending generation.

It boils down to: Can we wait until #100 is fixed before releasing test builds? If yes, close this. Otherwise, merge this.

**Comment by amulware** [comment]
We can wait for #100, but let's get around to that soon then.

**Pull request closed without merging**
