### PR TITLE
🚧 Finish/fix external calendars sync

### LINKED ISSUE #7708: Get selected external calendars
## Description
We need to add the new endpoint to fetch the selected external calendars

## Definition of done
- [ ] New endpoint is added

### PR DESCRIPTION
**Pull request by juanlaube**
## What's this?
This fixes and finish the external calendar events sync. Since we started some properties changed, the endpoints changed and there were some bugs.

### Relationships

Closes #7708 

## Why do we want this?
We want to use the external calendars.

### Side effects
None.

## Review hints
If you want to test it, I can help you to set up everything in staging to test this, let me know.

## :squid: Permissions
🦑

### CODE REVIEW

**Comment by sofokli1** [comment]
how can i test this?

**Comment by sofokli1** [comment]
or do you just need a 👍 ?

**Comment by juanlaube** [comment]
@sofokli1 to test:
- Open the web browser inspector in beta.toggl.space and in the console enter `toggl.egg.setCalendarIntegrationsBeta(true);`
- In the user profile, you can now link your google calendar account (only works with the toggl g suite account for now)
- After you finish the login it will fail (because some staging urls), change the redirect url to `beta.toggl.space`
- Now when the app resumes from background (I still have to add this to a cold start) it should fetch the calendar data, you can add some breakpoints to `SyncExternalCalendarsInteractor` to see it working, nothing will appear in the UI yet.

**Review by sofokli1 — APPROVED** [review]
despite the steps I couldn't make beta.toggl to show me the cal. since this is going to the project branch I think it is ok as is. will test when it comes all together there. Code wise looks ok

**Pull request merged**
