### PR TITLE
Burn stale binding infra

### LINKED ISSUE #3869: Remove all the MvxBinding junk from the app
Doable only once all views are RxFactored. We need to remove:

- [x] The `Bindings` folder from both `Daneel` and `Giskard`
- [x] The `Combiners` folder from `Foundation`, `Daneel` and `Giskard`
- [x] The `Converters` folder from `Foundation`, `Daneel` and `Giskard`
- [x] The `SetupTargetFactories.tt` from `Daneel` and `Giskard`
- [x] Everything that's no longer needed from `LinkerPleaseInclude.cs`. Let the linker strip all of that away!

### LINKED ISSUE #3870: Remove PropertyChanged.Fody from the app
Once all views are RxFactored, we'll no longer need to rely on this, so we can sefely remove it from Foundation, Daneel and Giskard.

### PR DESCRIPTION
**Pull request by heytherewill**
## What's this?
This is a huge fire that burns away a lot from the MvvmCross binding infrastructure that we no longer need.

This is still WIP since there are a couple of PRs that need merging!

### Relationships
Closes #3869 
Closes #3870 

Depends on
* [x] #4353 
* [x] #4434 
* [x] #4486 
* [x] #4562

## Why do we want this?
🔥 MvvmCross

## How is it done?
I literally just delete the files

### Side effects
That's a good one: This might actually make the app thinner and faster. I'll measure app weight once this branch builds and check app performance once this is released to users

## Review hints
Reviewing by commit is a lot nicer

## :squid: Permissions
Anyone

### CODE REVIEW

**Comment by juanlaube** [comment]
This is looking good because 🔥 🔥 🔥 🔥 🔥 
That being said, it doesn't build and I've noticed some files still have `using PropertyChanged;` and some properties are still annotated with `[DependsOn(...)]`

**Comment by amulware** [comment]
Please report back to me RE app size and performance once the data is available!

**Comment by kornelijepetak** [comment]
@heytherewill All of the dependencies are resolved. However, I can still see a bunch of `local:MvxBind`s in `.axml` files. Should this issue include these rxfactorings?

**Comment by kornelijepetak** [comment]
One thing more I've noticed is that the `strings.xml` on Giskard still contains the template selectors strings. Remove those as well and ping me to approve.

**Pull request merged**
