### PR TITLE
Android 2.5 Faloodeh

### PR DESCRIPTION
**Pull request by pdrj**
# User facing
- Added sync status next to the logout button
- Fixed a bug which made syncing appear to take forever
- Fixed a crash that occurred when filtering lists
- Fixed visual glitches in the pie chart
- Fixed an empty view presented when selecting a default workspace
- Fixed incorrect copy on the login page

# Internal
- Fixed rating view not being presented
- Made background sync use light sync, instead of full sync
- Added analytic events for calendar selection
- Enabled analytic events for background syncing

# Changes
https://github.com/toggl/mobileapp/compare/android-2.4.1...android-2.5-faloodeh

### CODE REVIEW

**Comment by amulware** [comment]
changelog suggestions:
- Added before Fixed
- Fixed a but which MADE (past tense) syncing appear to take forever (simplify sentence)
- Fixed a crash THAT OCCURED (less colloquial) when filtering lists
- Fixed INCORRECT (it's not all) COPY ('text' sounds funny to me 🤔) on THE (article) login page

**Comment by pdrj** [comment]
Applied your suggestions @amulware. Thanks.

**Comment by pdrj** [comment]
Can I treat the changelog as 'reviewed' now? :)

**Comment by pdrj** [comment]
@amulware I've added:
>- Fixed an empty view presented when selecting a default workspace

does the changelog look good?

**Comment by amulware** [comment]
Fine by me :)

**Pull request merged**
