### PR TITLE
Fixed the Pixelation issue in the Pie Chart

### PR DESCRIPTION
**Pull request by kpv1993**
## What's this?
It is a bug fix for pixelation issue in the report screen for Pie Chart.

### Relationships
None

## Why do we want this?
The pie chart doesn't look good

## How is it done?
I added anti-aliasing which smoothens the edge.

### Why not another way?
Open to suggestions

### Side effects
None

## References
https://github.com/toggl/mobileapp/issues/2445

## Review hints
Before:
41299754-0fc1a0ac-6e5c-11e8-883b-6eadf9149c89

After:

Screenshot_20190807-225038

## :squid: Permissions
None

### CODE REVIEW

**Comment by daividssilverio** [comment]
This is actually nice.
The text paint could also use some anti-aliasing.
If there's an issue for this, could you please add the reference to your PR?
Also, capitalize the title of your PR.
If this is to be squashed, don't forget to follow our guidelines and add an emoji :art: in the beginning of the commit message.

**Comment by heytherewill** [comment]
What daivid said, please add anti-aliasing to the text paint as well and post the results 🙇

**Comment by kpv1993** [comment]
Will do the changes

**Comment by kpv1993** [comment]
I did the required changes. I will remember the commit thing

**Pull request merged**
