### PR TITLE
Giskard 1.13.1 - Hotfix

### LINKED ISSUE #4926: NullReferenceException in EditTimeEntryActivity.setupViews
## 💥 Crash Report
This supposedly happens to a significant number of users on 1.13, when they open the Edit View.

### 👥 Impact
Current rollout: 5% (halted)
By now, occured `65` times to `43` users. 

### 🔗 Context
In 1.13, the Edit View has been rxfactored. This error has not been seen on any previous build (the excepting method hasn't existed before 1.13).

### 🛰 Link
[AppCenter details.](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/1586665989u/overview)

### 📝  Exception & Stack Trace
Unfortunatelly, this is all there is:
`System.NullReferenceException: Object reference not set to an instance of an object`

```cs
EditTimeEntryActivity.setupViews ()
EditTimeEntryActivity.OnCreate (Android.OS.Bundle bundle)
Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
```

### PR DESCRIPTION
**Pull request by kornelijepetak**
#### Changes in `1.13.1`:

```
- Fixed the crash in the Edit View
```
* Closes #4926

#### Changes from `1.13`:
```
- Added support for grouping similar time entries

- Improved app stability

- Fixed duration input in the Wheel View
- Fixed incorrect display of duration in Wheel View
- Other fixes in the Wheel View 

- Fixed invalid color in the Calendar View

- Various other fixes and improvements
```

## Changeset
https://github.com/toggl/mobileapp/compare/giskard-1.13-2...giskard-1.13.1

### CODE REVIEW

**Comment by daividssilverio** [comment]
Where's the changelog in the PR?

**Comment by daividssilverio** [comment]
The changelog looks alright to me now.

**Comment by daividssilverio** [comment]
The branch code runs almost always fine on the emulator.
It crashes the first time you open the app. I'll create an issue for that. Maybe it's just my setup, but I guess it's worth checking.
It worked fine on my Note 9.

**Comment by kornelijepetak** [comment]
Replaced by #4945 because of bad branch naming.

**Pull request closed without merging**
