### PR TITLE
Make sure currently running time entry is always up to date

### PR DESCRIPTION
**Pull request by arturs105**
This makes sure that edits to time entries are are also displayed in currently running time entry.

### CODE REVIEW

**Comment by willsb** [comment]
I'd rather create an observable that's aware of the currently running TE:
`dataSource.TimeEntries.TimeEntryUpdated.Where(te => CurrentlyRunningTimeEntry != null && te.Id == CurrentlyRunningTimeEntry.Id)`

And then simply `.Merge` it with `dataSource.TimeEntries.CurrentlyRunningTimeEntry`

**Comment by arturs105** [comment]
I also wanted to add a test for this change, but the following didn't work:

```
var timeEntryBuilder = TimeEntry.Builder.Create(12).SetStart(DateTimeOffset.Now).SetDescription("");
var timeEntry1 = timeEntryBuilder.Build();
var timeEntry2 = timeEntryBuilder.SetDescription("Updated description").Build();
var subject1 = new BehaviorSubject<IDatabaseTimeEntry>(null);
var subject2 = new BehaviorSubject<IDatabaseTimeEntry>(null);
DataSource.TimeEntries.CurrentlyRunningTimeEntry.Returns(subject1.AsObservable());
DataSource.TimeEntries.TimeEntryUpdated.Returns(subject2.AsObservable());

await ViewModel.Initialize();
subject1.OnNext(timeEntry1);
subject2.OnNext(timeEntry2);

ViewModel.CurrentlyRunningTimeEntry.Should().Be(timeEntry2);
```

**Comment by willsb** [comment]
Did it work with the previous code? What's the issue you're having?

**Comment by arturs105** [comment]
`ViewModel.CurrentlyRunningTimeEntry` is null. But if i comment out `DataSource.TimeEntries.TimeEntryUpdated.Returns(subject2.AsObservable());`, then it is `timeEntry1`

**Comment by willsb** [comment]
Is this ready for being reviewed?

**Comment by arturs105** [comment]
k7ieq0f

**Comment by willsb** [comment]
We are now using the `ITimeEntry` pumped by the Update observable in the main thread, so you need to make sure that it's not a `RealmTimeEntry`.

This is starting to smell bad, though. One possible approach would be exposing some time other than `ITimeEntry` as the currently running time entry. 

☝️  What do you think, @amulware @simonrozsival?

**Comment by willsb** [comment]
This will become obsolete because of the PR I'm working on for #510

**Pull request closed without merging**
