### PR TITLE
Losing and gaining access to workspaces

### LINKED ISSUE #3374: Set up syncing graph for losing and gaining access to workspace
Depends on #3372 

The order of states during `pull` sync should be this:

- `FetchAllSinceState`
- `DetectLosingAccessToWorkspacesState` (#2899)
- State from #3357 
    - if there are new workspaces -> go to state #3436 and then to  #3358, from this state always loop back to `FetchAllSinceState`
    - else continue to `persistWorkspaces`

### LINKED ISSUE #3375: Setup syncing graph for ghosts clean-up
This issue should replace #2640.

We should add a simple sequence of states into the clean-up sync loop:
1. remove ghost time entries (#2631)
3. remove ghost tasks (#3362)
2. remove ghost tags (#2633) (2. and 3. can be swapped)
4. remove ghost projects (#2634)
5. remove ghost clients (#2635)
6. make sure user's default workspace is not a ghost workspace (#3363)
7. remove ghost workspaces (#3361)

### PR DESCRIPTION
**Pull request by simonrozsival**
## What's this?
This is a long-living branch for the NSync project.

While we merge most of our PRs into the `develop` branch to be always up-to-date and avoid as many merge conflicts in the future, the code won't be actually used until we set-up the sync graph correctly - and we won't merge that into develop until everything is ready. This branch is intended to gradually create the syncing graph and merge it in the end.

### Relationships
Closes #3374 
Closes #3375 

## :squid: Permissions
Do not even think about it at the moment.

### CODE REVIEW

**Comment by simonrozsival** [comment]
Final sync graph: [nsync-graph.svg.zip](https://github.com/toggl/mobileapp/files/2556769/nsync-graph.svg.zip)

**Comment by simonrozsival** [comment]
`sh build.sh --target Tests.Sync`: https://app.bitrise.io/build/fa52ea21549ec8c4

**Comment by amulware** [comment]
For reference, I checked very little code. I mostly analysed the graph.

**Comment by simonrozsival** [comment]
Thanks for all the notes and ideas!

- I agree we could have some documented naming conventions and refactor the code accordingly, please create a simple issue for this, we can deal with this later "when we have time"
- `CleanUp` runs once when you lose access to some workspace(s) and then it runs once every day (“after midnight”). That’s why we didn’t bother with optimizing performance too much - it runs only once per day and in background. I'm not against some simple optimizations like "no inaccessible workspaces -> skip all these states", I will create an issue for that and we could manage to implement this today, sounds easy.

**Comment by simonrozsival** [comment]
Sync tests: https://app.bitrise.io/build/fafe4425e6851317

**Comment by simonrozsival** [comment]
Integration tests: https://app.bitrise.io/build/0122a9695e60e4c6

**Comment by simonrozsival** [comment]
Rebuilding sync tests: https://app.bitrise.io/build/05eb98c521f1e7ac

**Pull request merged**
