### PR TITLE
Add Android version of Login screen

### PR DESCRIPTION
**Pull request by kornelijepetak**
## What's this?
Android version of 

### Relationships
Solves part of #3969 
Requires #3968 to be merged first for proper diff.

## Why do we want this?
To simplify user experience.

## How is it done?
Just using the new ViewModel.

### Side effects
Requires testing.

## Review hints
Commit-by-commit.

## :squid: Permissions
Me.

### CODE REVIEW

**Comment by heytherewill** [comment]
Is this diff correct? It looks like it ain't

**Comment by kornelijepetak** [comment]
@heytherewill under Relationships it says:

`Requires #3968 to be merged first for proper diff.`

I branched off of that cause I needed the VM.

**Comment by kornelijepetak** [comment]
But for reasons of diff, I have now changed the base branch and will rebase on the `project` one after #3968 is merged.

**Comment by simonrozsival** [comment]
Then maybe this PR should be `on-hold`?

**Comment by kornelijepetak** [comment]
Temporarily closing until 🔑 Project is resumed..

**Pull request closed without merging**
