### PR TITLE
🕳️

### PR DESCRIPTION
**Pull request by amulware**

### CODE REVIEW

**Comment by khoi** [comment]
LGTM

**Comment by amulware** [comment]
Please let me know what lines are problematic for you exactly, and I'll see if I can remove them.

**Comment by khoi** [comment]
Line `` is not following our coding convention, kindly update it.

**Comment by amulware** [comment]
Doesn't work for me :(

**Comment by amulware** [comment]
Ah well, I don't think this'll ever pass review... I'll close it and try again.

**Comment by ApocalypticFish** [comment]
It did work for me, but didn't have notifications so I'm late to the party.

**Pull request closed without merging**
