### PR TITLE
Syncable repository

### PR DESCRIPTION
**Pull request by simonrozsival**
This repository extends the basic one with the functionality of returning the entities, which should be synced with the server.

### CODE REVIEW

**Comment by amulware** [comment]
Why do this in a new repository, instead of just having a query on the existing one?

**Comment by simonrozsival** [comment]
I wanted to stick to the open/closed principle (SOLID). It seems like a good idea here - I also didn't want to make the `IRepository` interface leaky again (@willsb).

**Comment by amulware** [comment]
I'm not sure I understand.

Why cant:
```
.Where(needsSync).OrderBy(lastChangeSelector).FirstOrDefault()
```

Be run on the existing repository?

**Comment by amulware** [comment]
Shouldn't that... just work?

**Comment by amulware** [comment]
(Assuming we use expressions instead of funcs, which it should do anyways.)

**Comment by simonrozsival** [comment]
After internal discussion we decided we don't need this.

**Pull request closed without merging**
