### PR TITLE
🤜 Add Sync Push actions classes

### LINKED ISSUE #7280: Create models for push actions
## 🎯 What needs to be done?
There are three actions that need JSON-serializable models:

* Create action
* Update action
* Delete action

Make those models according to sync API format.

## 🏆 Outcome
The models exist that allow serialization to JSON.

### PR DESCRIPTION
**Pull request by kornelijepetak**
## What's this?
Adds the Push Actions classes for Sync.

### Relationships
Closes #7280 

## Why do we want this?
To utilize the new sync API.

## How is it done?
Just some classes. I decided not to make things too generic as there's no particular appeal in doing that, since that would require introducing more interfaces which I'm not really eager to do.

## Review hints
Requires first look.

## Tests
Do we want/need tests for this?

## :squid: Permissions
Only Sync Team.

### CODE REVIEW

**Comment by simonrozsival** [comment]
Let's add some tests 👍

**Comment by daividssilverio** [comment]
What do you mean by "Requires first look"?

**Comment by kornelijepetak** [comment]
> What do you mean by "Requires first look"?

🤔 This will sound insane, but I can't remember that I've even written this sentence at all...

The closes I can get to what I _think_ I wanted to say is: Requires first looking whether the approach is good. But I really don't know.

**Comment by kornelijepetak** [comment]
@daividssilverio wanna add something or can I ignore your comments for purposes of merge?

**Comment by daividssilverio** [comment]
Go ahead and merge it o/

**Pull request merged**
