### PR TITLE
🚧 Add NoProject UI Test

### LINKED ISSUE #4178: Start TE: Test "No Project" Option
Sign in
Start a time entry
Enter project selection screen
Select "No project"
Save entry
Stop entry
Successful sync status displayed?

### PR DESCRIPTION
**Pull request by sofokli1**
## What's this?
UI Test for when no project is selected from the project list in start view.

### Relationships
Closes #4178

## Review hints
I am having trouble with this test. I can't find a way to check for the lack of something (like the lack of project label in a cell). Also not much luck in trying to find `UITableTextAccessibilityElement`

## :squid: Permissions
No

### CODE REVIEW

**Comment by heytherewill** [comment]
Lack of something can be tested with `WaitForNoElement`, and you should look into setting the accessibility label from .xib. I can help you if this is not clear :)

Also, it looks like this a WIP. If so, if should be tagged as such

**Comment by ApocalypticFish** [comment]
There is a menu option that shows up once you enter the @ symbol or press project selection. We did have an issue where pressing this specifically caused crashes so the test was intended to test for this.

**Comment by sofokli1** [comment]
@ApocalypticFish Please take a look again

**Comment by sofokli1** [comment]
@heytherewill you ok with this?

**Comment by heytherewill** [comment]
Yup!

**Pull request merged**
