### PR TITLE
iPad: The Final Mergeback

### PR DESCRIPTION
**Pull request by dshr**
## What's this?
The mergeback to end them all.

### Relationships
Closes nothing

## Why do we want this?
To ship our iPad version.

## Review hints
Go commit by commit — this way the amount of weirdness is contained into little separate boxes.

## :squid: Permissions
iPad crew, I choose you!

### CODE REVIEW

**Comment by sofokli1** [comment]
@dshr should this view be this tall?

Simulator Screen Shot - iPad Pro (11-inch) - 2019-04-04 at 13 06 34

**Comment by sofokli1** [comment]
also can't see the bottom of the create view when keyboard is up (which is always)
Simulator Screen Shot - iPad Pro (11-inch) - 2019-04-04 at 15 07 13

**Comment by sofokli1** [comment]
the project name are not aligned correctly. I see 4 cases
1. there is a description
2. there is no description
3. grouped main cell with description
4. grouped main cell without description
Simulator Screen Shot - iPad Pro (11-inch) - 2019-04-04 at 15 33 13

**Comment by Odrakir** [comment]
All I’ve seen has already been mentioned. The parts of the code I know of are ok.

**Comment by dshr** [comment]
Squashed all my commits into one in order to keep our git logs neat and tidy.

@sofokli1 the project labels problem is outside the scope of a mergeback, so I'll do a separate PR for it. I've discussed it with @maritoggl as well, and we might just leave it as it is for the time being.

**Pull request merged**
