### PR TITLE
Add timer suggestion cell

### PR DESCRIPTION
**Pull request by arturs105**
Used to display suggestions. Can be seen in #78.

### CODE REVIEW

**Comment by arturs105** [comment]
Just noticed that the last cell in the image doesn't have a project label. Should that be a different cell or should this cell be rearranged if the project is not set?

**Comment by amulware** [comment]
I think it should be the same cell. I much rather have the branching logic right there in the UI, than having to create different views based on the model.

**Comment by willsb** [comment]
I strongly disagree, Paul. No reason for increasing the complexity of a View when we can simply add multiple files.

**Comment by amulware** [comment]
You rather duplicate virtually the entire view for a slight difference in layout? And if the design changes change both?

**Comment by arturs105** [comment]
Bottom row (`ProjectLabel` and `TaskLabel`) can be removed by setting `BottomRowView.Hidden = true`, `DescriptionLabel` will automatically recenter.

**Pull request merged**
