### PR TITLE
Android toolbar color overhaul

### PR DESCRIPTION
**Pull request by heytherewill**
## What's this?
This makes our toolbars consistent.

## Why do we want this?
The current app is a mess with a multitude of colors.
Now it's consistent and follows the material design guidelines.

## How is it done?
All toolbars are now white.

## Review hints
Please review this thoroughly and go through every single screen of the app to make sure we're not missing stuff.

## :squid: Permissions
Only myself

### CODE REVIEW

**Comment by amulware** [comment]
Please present screenshots of various screens, including with/without projects, and different (light/dark/medium) project colours for discussion and review by @maritoggl and me internally. On hold until we decide how far to go with this.

**Comment by heytherewill** [comment]
I'm removing the `on-hold` status since Mari agreed we should continue with this :)

**Comment by juanlaube** [comment]
This is what I mean @heytherewill. In `develop`, the vertical separators in the header and the recycler view are aligned and it looks like a single line.
Screenshot_1565093741

**Comment by heytherewill** [comment]
Good comment, Daivid. I guess I'll submit a PR to migrate everything towards `app:droidStuff` :)

**Pull request merged**
